### ISSUE TITLE
[Feature Request] NodeJS API for rendering an adaptive card to an image

### ISSUE THREAD

**Issue by robinsedlaczek** [microsoft/AdaptiveCards#1012]
## Feature Request
We need a NodeJS implementation that renders an adaptive card to an image. Only a simple default design is needed, e.g. the card design of WebChat. The service works async and returns at least a byte stream of the image.

This issue was created in addition to closed issue #930.

## Evaluated NodeJS packages

tbd

**Comment by Claessens14** [comment]
Could we get an update on where this feature stands, I would find it useful. 
Thanks.

**Comment by srozga** [comment]
You can do this yourself fairly easily as follows:

1. Render your adaptive card into HTML. You can use this library. [Adaptive Card to HTML client](https://docs.microsoft.com/en-us/adaptive-cards/display/libraries/htmlclient). I'm not sure what styling it uses by default, but you can use the default or provide a HostConfig to guide to specify styling.

1. Use a library like [Puppeteer](https://github.com/GoogleChrome/puppeteer) to render HTML into a png. Puppeteer is a node library to control a headless instance of Chrome. We use it very effectively.

A few caveats. If you are satisfied with the rich layout control Adaptive Cards provide, this is a great approach. Not to state the obvious, but make sure you don't leave features in your card that don't make sense in an image. Input fields come to mind. Lastly, if you need 100% fine tuned control over an image or want to generate a graphic using standards compliant HTML/CSS/JS, just create your own HTML by hand and go straight to Puppeteer. 

We have been using this approach in production for almost six months. We have not have any issues with the approach.

**Comment by Claessens14** [comment]
@srozga  thanks for the insight, for me its best to use a renderer since since I already have adaptive cards made. I am using node.js and trying to use the solution outline above, however I cant seem to run the code from the [link](https://docs.microsoft.com/en-us/adaptive-cards/display/libraries/htmlclient). The adaptive card npm module seems to crash because I dont have a document object defined. 

```
(node:7368) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined  
at AdaptiveCard.Container.internalRender (C:\Users\Jacob\Desktop\advisor-chatbot\node_modules\adaptivecards\lib\card-elements.js:2403:23)
    at AdaptiveCard.ContainerWithActions.internalRender (C:\Users\Jacob\Desktop\advisor-chatbot\node_modules\adaptivecards\lib\card-elements.js:3161:55)
    at AdaptiveCard.internalRender (C:\Users\Jacob\Desktop\advisor-chatbot\node_modules\adaptivecards\lib\card-elements.js:3347:63)
    at AdaptiveCard.CardElement.render (C:\Users\Jacob\Desktop\advisor-chatbot\node_modules\adaptivecards\lib\card-elements.js:324:38)
    at AdaptiveCard.render (C:\Users\Jacob\Desktop\advisor-chatbot\node_modules\adaptivecards\lib\card-elements.js:3441:52)
```

I assumed that document object can be defined in puppitteer instance, but since I am not familiar with client side js / puppiteer pages, I dont know how to have adpative card renderer recognize the document object, so that the renderer doesnt fail. 
Let me know what you think, thank you.

**Comment by rcasto** [comment]
@Claessens14  Yeah, that's happening because the [Adaptive Card to HTML client library](https://docs.microsoft.com/en-us/adaptive-cards/display/libraries/htmlclient) does not yet support rendering Adaptive Card JSON in node.js environments, it assumes its being used in the browser context.  I've opened issue [#1274](https://github.com/Microsoft/AdaptiveCards/issues/1274) on that topic.  You can hack it though if you want and use [jsdom](https://github.com/jsdom/jsdom) to shim browser global variables within node.js

**Comment by Claessens14** [comment]
@rcasto thanks for [link](https://runkit.com/rcasto/adaptive-card-nodejs), I can now convert the card to an HTML, and then take the screenshot with puppeteer. However, did you encounter any rendering problems also, such as the markdown styling or am i just missing something, because my rendering if different from the [sample](http://adaptivecards.io/samples/Restaurant.html) online. Note i also tried the markdown change mentioned in this [link](https://docs.microsoft.com/en-us/adaptive-cards/display/libraries/htmlclient).


![alt text](https://i.imgur.com/smSwEkl.png  "Logo Title Text 1")

**Comment by rcasto** [comment]
@Claessens14  Nice!  I did that more as an example for the issue, didn't get to any cards with markdown.  The Adaptive Card to HTML library by default looks for the [markdown-it](https://github.com/markdown-it/markdown-it) library in the global window scope to process the markdown.  If it's not there, it will just return whatever the [markdown/text was without processing it](https://github.com/Microsoft/AdaptiveCards/blob/616378d7555c684082e85523d35803951605c2e5/source/nodejs/adaptivecards/src/card-elements.ts#L3840).  To fix it you could override the default processMarkdown method to use a markdown to HTML library of your choosing by doing something like:
```javascript
var markdownLibrary = require('some-markdown-library');
AdaptiveCards.AdaptiveCard.processMarkdown = function (text) {
    return markdownLibrary.toHTML(text);
};
```

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
