### ISSUE TITLE
Render to image with WPF does not work on server

### ISSUE THREAD

**Issue by robinsedlaczek** [Microsoft/AdaptiveCards#1038]
@matthidinger Hi Matt! I feel sorry, but I still have the rendering problem. I have a web service that performs the rendering of an adaptive card to an image. This web service is using the API you provided with #930. I host the service in Azure. After you stated that everything is working again in #985 I updated all NuGet packages in my service implementation and deployed the service again to Azure. But images are still rendered as blank images. To verify, I created a second resource group and deployed the service to another location. First was East US, second resource group was created to be in West US.

![image](https://user-images.githubusercontent.com/2900224/33817086-d08cea1c-de3d-11e7-80a9-a035188226c8.png)

But same problem: blank images. Below you can see the overview of both services from my Azure portal. Isn't the location selected for the resource group the same location where services in this resource group are hosted? I am wondering why both services state that they are running in South Central US. And wasn't the patch rolled out everywhere?

Would be great if you can have a look at this issue. Want to present Adaptive Cards on a conference tomorrow. Hopefully we get it running until my talks.... :) 

![image](https://user-images.githubusercontent.com/2900224/33817097-e8d4b7c6-de3d-11e7-9fbd-015222dc8b2e.png)

![image](https://user-images.githubusercontent.com/2900224/33817104-ece874b0-de3d-11e7-8a5a-1eae994d29e7.png)

Many thanks in advance!

Robin

**Comment by matthidinger** [comment]
Hi Robin, I really wish I had better news for you :( 

The reason we were able to get Bot Framework image rendering fixed is because we host our own servers and were able to patch them manually. It's a pain, but if you wanted to do the same for your demo you would have to spin up a VM I think. For standard Azure app services we have to wait for Azure's normal patch rollout, and I have no idea what their timelines are for something like that. I will try and dig up more information from the Azure folks and let you know if I hear anything. Sorry about the troubles here -- really bad luck with timing!

**Comment by robinsedlaczek** [comment]
@matthidinger Hi Matt! Thx for the fast reply! Ok, no hurry. I'll fire up my service in an own environment. But only temporary, will return to Azure asap! ;) Think we have to wait until Windows Server 2016 is rolled out in January 2018, or? Maybe the affected infrastructure covers the place where my little web api is running. :)

Thx again for your fast answer!

**Comment by matthidinger** [comment]
Hey @robinsedlaczek this should be working now, please let me know if you're still seeing any issues
