### ISSUE TITLE
Image "includeQueryParameters" property would append attributes like scale and high-contrast 

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#106]
Remote images need context about the client to ensure the image will look correct. 
```
{ 
"type": "Image"
"url": "http://bing.com/sunny.png",
"includeQueryParameters": true
}
```
When `includeQueryParametersis` is true we will append query string params to the request that the client can use to generate properly.

## Suggested query params:

**ms-scale** a scale factor that is recommended based on the DPI of the device
**ms-contrast** - whether the device/app is operating in a high-contrast mode
**ms-lang** - the language the device is in

## Stretch goal:
**ms-background-color** - provide the background color of the Card so that the generated image can feel native with the rest of the content

## Context from Notifications 
https://msdn.microsoft.com/en-us/library/azure/mt587306.aspx

Set to true to allow Windows to append a query string to the image URI supplied in the tile notification. Use this attribute if your server hosts images and can handle query strings, either by retrieving an image variant based on the query strings or by ignoring the query string and returning the image as specified without the query string. This query string specifies scale, contrast setting, and language; for instance, a value of www.website.com/images/hello.png included in the notification becomes www.website.com/images/hello.png?ms-scale=100&ms-contrast=standard&ms-lang=en-us.

**Comment by matthidinger** [comment]
Todo on @matthidinger: spec the params values.

**Comment by WiCarr** [comment]
One thing that could be helpful is providing the Adaptive Card author with some hints as to how the Renderer is sizing the image element.

If you're using a Background Image one Renderer may be using a Portrait card while another may be using a Landscape card. There's no way for the image provider to choose the asset best suited for the resultant aspect ratio (or even to specify how the image ought to be fitted into the aspect ratio) today.

If there were ever an option introduced to explicitly have an image take up the full size for one of the aspects it would also benefit from this (I could see this being a common request for cards that want to show a rich image along with a title or caption that isn't overlayed).

In some cases it could be very useful if an adaptive card could easily pass the exact Width & Height of the image element as explicit arguments, since some images can be sourced by REST APIs which may already provide options for Width and Height. As an example consider an app using the Bing Maps Imagery REST API to get a static map image using the mapSize parameter: https://msdn.microsoft.com/en-us/library/ff701724.aspx.

In other cases it may just be useful to know the aspect ratio of the image element (or card in the case of a background image) in order to choose the best source image (although even here size would still be interesting since you could choose the best sized image for the card).

In other cases an option to choose between some standard image positioning types (stretch, fit, fill, center) could be useful if there is a single source image that will look best with a particular positioning.

**Comment by anbare** [comment]
Closing in favor of #1648
