### ISSUE TITLE
What is the difference between adaptivecards.io and messagecardplayground.azurewebsites.net

### ISSUE THREAD

**Issue by vxnsbir1ugsp** [Microsoft/AdaptiveCards#1070]

**Comment by dclaux** [comment]
@vxnsbir1ugsp the MessageCard Playground is Outlook specific and is a tool to create Actionable Message cards (see https://docs.microsoft.com/en-us/outlook/actionable-messages/). The visualizer on adaptivecards.io is a generic design tool for Adaptive Cards. Both tools have the same original code base, which is why they look so much alike.
