### ISSUE TITLE
Toggle the adaptive card elements by Input.Toggle

### ISSUE THREAD

**Issue by CalvinFengDatacom** [microsoft/AdaptiveCards#1339]
I just wondering, is there a way that I can use Input.Toggle to toggle displaying or hiding the other adaptive card elements within one card?

I can see, currently, Input.Toggle is only used for toggle between two options. But, does anyone who knows how to toggle the adaptive card elements?

**Comment by dclaux** [comment]
@CalvinFengDatacom currently this isn't possible out-of-the-box. You can achieve this via extensibility but only using the HTML renderer, because currently it is the only one that supports toggling the visibility of individual elements.

What you would need to do is create your own Input.Toggle implementation and handle toggling the visibility of elements as the toggle is checked/unchecked.

I think this kind of functionality could be a great addition to Adaptive in the future. Let's keep this in the back log

**Comment by CalvinFengDatacom** [comment]
@dclaux  Thank you for your response, I think this is quite important. In most business cases, they do prefer having such kind of functions in adaptive card.

**Comment by andrewleader** [comment]
Hey @CalvinFengDatacom, to clarify, do you want to have a Toggle input (checkbox) and depending on whether that checkbox is checked, show/hide other content?

If you don't need a checkbox, we just added `Action.ToggleVisibility` in 1.3 ([see it here](https://adaptivecards.io/explorer/Action.ToggleVisibility.html)).

Please clarify whether you need this toggling of visibility to be based on the input value of a checkbox! Thanks!

(Closing the issue for now as we've captured this feedback in our feedback system, feel free to still respond)

**Comment by CalvinFengDatacom** [comment]
Hi @andrewleader , This is what we were looking for, but for our last project we found another alternative way to design this requirement. 
But, it's good to know this method, and thanks for letting me know. :-)
