### ISSUE TITLE
[.NET] Add support for card-level selectActions

### ISSUE THREAD

**Issue by khouzam** [Microsoft/AdaptiveCards#1349]

**Comment by tuanh118** [comment]
I've added support for card-level `selectAction` and have a couple of general observations for `selectAction`:
* Inline ShowCard doesn't work
* Date input in popup card doesn't work
* Action.Submit contains data from various Input elements
* Overlapping selectActions are all triggered when clicked

Since these behaviors are shown for all kinds of `selectAction` (in `Container`, `ColumnSet`, `Image`), I should ignore them for this issue and create other issues right?
