### ISSUE TITLE
[TS] Media player support

### ISSUE THREAD

**Issue by khouzam** [Microsoft/AdaptiveCards#1361]

**Comment by dclaux** [comment]
@ignacionr would you want to help (again)? This feature is somewhat expensive because to do it properly the playback controls have to be owned by the Adaptive renderer, the standard HTML5 player controls just won't do because:

1. They can't be styled, and will end up looking bad in many cards
2. They are rendered differently in every browser

You might argue that's ok, but on top of that the standard controls for the <audio> tag don't even resize, making it a requirement for Adaptive to render its own controls.

So far I haven't had time to implement this, so if you want to give it a shot, you are more than welcome.

**Comment by ignacionr** [comment]
@dclaux I had read your previous comment on those required limitations, and understand the reason.
Super happy to help; let's check again by Friday 8th see where I've gotten. Sounds like a plan? (By the way I thought you'd reply after the Monday meeting -didn't mean to have you working on a Sunday.)

**Comment by dclaux** [comment]
@ignacionr sounds good.

**Comment by ignacionr** [comment]
@dclaux I'm going with controls rendered as anchors, _under_ the video for starters (will share a screenshot soon); can you explain what is the intention when there are multiple sources (is it intended as alternatives or as a sequence?)

**Comment by dclaux** [comment]
@ignacionr whatever works, feel free. Let me just give you a dump of what matters most:
- Don't use third party controls (e.g. no dependency on another library)
- Don't have dependencies on external images for buttons
- Don't have a dependency on an external color font
- Make sure that the control bar in its entirety reflows well when space is limited. I don't think we want controls to wrap, for instance

- Make sure the whole control bar can be styled via the Adaptive CSS file


As for how things are supposed to work with sources:

- Go through the list
- Valid sources will have their `mimeType` starting with either **audio/** or **video/**. All other MIME types are ignored
- The first valid MIME type determines the type of media the player will play (audio or video)
- At that point, drop all sources that are not of that type, and feed the list of remaining sources to your `<audio>` or `<video>` HTML element
- If you don't find any valid sources, render the poster instead. Poster should likely be rendered like a stretched image would be. If there is no posted on the Media element, rendere the default poster from HostConfig. If there is no default poster, feel free to come up with a creative fallback strategy :)
- When you do render the poster, overlay a "play" button in its center; when clicked, this button would open the first of the original sources (regardless of what it is) in a separate browser window (or tab)

**Comment by andrewleader** [comment]
Looks like we forgot to close this, closing
