### ISSUE TITLE
[Feature Request] Add ability to completely unset styles via HostConfig

### ISSUE THREAD

**Issue by jkymarsh** [microsoft/AdaptiveCards#1389]
From what I can tell, the HostConfig doesn't currently allow you to do two things:

1. Set values to 0 (or whatever the default "none" value is for a specific property)
2. Unset specific styles entirely by either omitting them or supplying a default value ("nothing", false, etc.)

It'd be really nice to have some sort of way to prevent inline styles from being generated on elements **at all**, for those of us attempting to more heavily style components. It would seem cleaner to allow developers to build the styles up, if desired, rather than the current strange hacks required to tear down/rewrite the existing inline styles.

**Comment by dclaux** [comment]
Thanks for the feedback.
Could you elaborate which inline styles you would like to be able to completely override? Maybe a couple concrete examples?

**Comment by jkymarsh** [comment]
To be completely honest, my response to that would probably be "all of them."

Most people implementing client-side chatbot implementations, such as myself, are probably developing their own UI to some extent - either a themed variant of an existing chatbot UI tool or a from-scratch implementation. In both cases, having a ton of inline CSS, as AdaptiveCards do, make it super irritating to achieve modifications to the cards.

Presently, my CSS to modify AdaptiveCards consists of a wrapper class at the top level, and then I have to use a bunch of insane traversal to unstyle/restyle specific elements. Styling things properly - that is, using CSS classes and external styles - would make everything a trillion times more usable.

**Comment by dclaux** [comment]
If you had a concrete example of before/after your restyling, that would be very helpful.

The Adaptive Card renderer making it hard to fully restyle is by design; the renderer wants to keep control over the layout and many styles are expressed via HostConfig, making them somewhat incompatible with the use of CSS. For example, the renderer needs to have control over "line-height" and simply can't let that be specified in CSS (and by "can't" I mean it could at the cost of way more complicated code and much worse performance.
