### ISSUE TITLE
Different styles for different buttons

### ISSUE THREAD

**Issue by rednivrug15** [Microsoft/AdaptiveCards#1541]
Currently the same style can be specified for all buttons and there is no way to show a spinner/loading animation on the buttons as the view of the button is not returned . Consider returning the view of the button when the button is pressed or allow overriding of buttons.

(Original request is for Android renderer)

**Comment by anbare** [comment]
Hey @rednivrug15, can you provide some more details around this scenario?

Would it make sense for you to draw a spinner/loading animation over the **entire** card, rather than the specific button that was clicked? I imagine you wouldn't want the users to click other buttons while an action is currently being executed.

**Comment by khouzam** [comment]
This has been merged.
