### ISSUE TITLE
Support different button styles for image buttons vs normal text buttons

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1578]
When buttons (actions) have icons, we want our buttons to be styled differently than when the buttons don't have actions.

What we get today...

![image](https://user-images.githubusercontent.com/13246069/41180443-243dd3f2-6b23-11e8-9f06-052e87ff0f29.png)

What we want these to look like...

![image](https://user-images.githubusercontent.com/13246069/41180645-b7ae3a50-6b23-11e8-9f33-cd4f84014fa6.png)

But when buttons don't have icons, we want them to look like...

![image](https://user-images.githubusercontent.com/13246069/41180752-1978842a-6b24-11e8-8802-93f97562e233.png)

**Comment by Kartik1607** [comment]
I think this can be achieved by using column sets and adding actions on them. Create different adaptive card for when you have icon and when you dont.

**Comment by anbare** [comment]
Unfortunately it can't, this needs to be controlled by the host and be consistent (just like how normal actions are consistent).

Otherwise if in the future we decide that the buttons should now be accent colored, we would have to ask all app developers to update their column set backgrounds... we lose all host consistency.

**Comment by andrewleader** [comment]
Closing as this might/should be possible today, plus no active requirements
