### ISSUE TITLE
[TS] Consider splitting card-elements.ts into per-class files

### ISSUE THREAD

**Issue by ignacionr** [microsoft/AdaptiveCards#1652]
It would take some coordination. I know it's painful. Also it's likely in your head you have some broader plan (e.g. to separate the parsing from the rendering, as happens with the C++ code base).

But let's rather do this before reaching 10k lines of code?

**Comment by dclaux** [comment]
No plan to separate the parsing from the rendering, that is by design. Splitting into per class files has its challenges, with CardElement referencing Action and Action referencing CardElement, but yes, I think eventually we'll want to do that.

**Comment by ignacionr** [comment]
Right. The parent could become an interface instead of a class. Something that provides the services in CardElement we're using from Action.
If this change will happen, wouldn't you agree we rather do it sooner than later?

**Comment by ignacionr** [comment]
This simple change:

<img width="367" alt="screen shot 2018-06-28 at 11 44 22 am" src="https://user-images.githubusercontent.com/1210985/42013697-b06c4c32-7ac8-11e8-9ede-de2883a07e5b.png">

plus changing the declaration of setParent() and parent() only on that class. This works AOK (tsc produces no issues, the derived setters still work, and tests pass).

**Comment by dclaux** [comment]
Sorry for the delay, I had missed your new comments on this. Yes, if we're going to do it, better sooner than later.

The goal for this work is that things work exactly as before after the changes though. E.g. no breaking change for developers who are using the renderer in their own app. Likely this is possible by introducing IAction as you suggest, but it might be more complicated.

I don't know when I'll have time for this (and honestly, to me it is not that important. I find that often people don't really know why they even want classes split into separate files other than "because it's better".) Is this something you would want to take a look at in addition to the Media element?

**Comment by ignacionr** [comment]
Thanks for your comments. I agree in general to what you say, as I value more “fluency” than file structure, and also couldn’t care less for an assumed value in just conventions.

On the other hand, while working on the Media element, it did happen that merging changes confused git causing extra work (a long file worked on different parts has greater chances of merge conflicts).

Yes, I would be happy to give this a try. Because it requires some coordination, is the code normally frozen over the weekend? Can we issue a request to the team to push this Friday, so they won’t find themselves losing stuff? Also the commit would need to be reviewed and merged with priority so to avoid missing changes in between.

Again, I’m game.
