### ISSUE TITLE
[JS] API to enumerate all images contained in a card

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#1660]
See parent #1094 for details

**Comment by matthidinger** [comment]
Hey @dclaux any chance we can squeeze this into the 1.1 release to keep API consistency?

**Comment by dclaux** [comment]
@matthidinger the API already exists and isn't limited to Image elements. Essentially you can walk the element tree with getElementCount and getElementAt, and extract all the Image elements as you go. It doesn't seem to me that there is a need to do anything beyond that. Am I missing something?

**Comment by andrewleader** [comment]
@dclaux that's not exactly the same. This API returns image URLs.

```csharp
var card = new AdaptiveCard();

List<Uri> resourceUris = card.GetResourceUris();
```

This means the host doesn't have to have knowledge of the object model nor the objects. For example, today, hosts would have to know "Oh there's such a thing as a background image", and when we add background images to containers, they'll have to know that too. Additionally, we added images to actions - hosts would have to learn that actions now have images too.

**Comment by dclaux** [comment]
Sorry, I should have looked at the spec. Made the wrong assumption as to what that API was about based on the title of this issue.

Makes sense, I'll add the method.

**Comment by andrewleader** [comment]
Awesome work!! I added one comment on the review about naming of the API based on the conventions the other renderers followed

**Comment by dclaux** [comment]
@andrewleader I am not seeing the comment for some reason. Anyway, I deliberately picked getAllImage**Urls** instead of getAllImage**Uris** because everything else in the Adaptive schema refers to URLs, not URIs (Action.**iconUrl**, Image.**url**, MediaSource.**url**, Action.**OpenUrl** and I might be forgetting some.) If anything, I think the other renderers should move to getAllImageUrls. If you really insist I can go with getAllImageUris, but it makes very little sense to me.

**Comment by andrewleader** [comment]
Whoops my bad, I didn't submit the review, just did it now. It's a bit more than url vs uri, but agreed about url :) In their RemoteResourceInformation class it is indeed url, consistent with the rest.

**Comment by khouzam** [comment]
Merged.
