### ISSUE TITLE
[.NET] Q: AdaptiveContainer

### ISSUE THREAD

**Issue by grahamehorner** [Microsoft/AdaptiveCards#1698]
I've been looking at the code base and I'm wondering why ColumnSet, ImageSet, FactSet are not derived from containers, as these objects contain elements in the form of Colums, Images, Facts ?

I'm also wondering why AdaptiveColumn, AdaptiveImage, AdaptiveFact don't derive from the AdaptiveTypedElement?  IMHO if they did it would make parsing/rending/databinding code easier to write as these base classes express/group object into their classification and provide common attribute/notation for de/serialization & converting.

**Comment by andrewleader** [comment]
For the first question: Containers take a list of AdaptiveElement, whereas FactSet only takes a list of Fact items. If we made FactSet (and the others) derive from container, then we wouldn't be able to enforce the type restrictions. We could use generic types and have a common base class, but we decided to leave them separate.

For the second question: They do? AdaptiveColumn and AdaptiveImage derive from AdaptiveTypedElement (that's their root base class).

It's only AdaptiveFact that does not, but that's because AdaptiveFact doesn't require the type property. It still certainly could benefit from the AdditionalProperties though, so a smaller base class could certainly make sense.

Closing this for now, re-open if you have more questions!
