### ISSUE TITLE
[ios] Show card should collapse on submit action

### ISSUE THREAD

**Issue by kratijain-microsoft** [microsoft/AdaptiveCards#1715]
# Platform
* iOS

# Author or host
Host : MS Teams ios

If you're an author, who are you sending cards to?
1.1

# Issue
On submit, show card doesnt close.

**Comment by nesalang** [comment]
@matthidinger can you please comment on this?

**Comment by matthidinger** [comment]
Hmm I'm not actually sure any of the renderers do this today. @dclaux can you confirm if the JS renderer has this behavior or an API to handle this? Either way we should document it and make sure all renderers are aligned

**Comment by andrewleader** [comment]
This needs to be something configurable by hosts. In Windows toasts, *we would want it to stay open*... that's because when submission happens, we animate the entire toast out. So if the show card content disappeared, that would look like a choppy and odd experience with that shown section disappearing while the toast is sliding out.
