### ISSUE TITLE
Automatic tooltip for TextBlock's that get clipped

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#1788]
We should consider applying a tooltip where possible on TextBlock's that are clipped either due to `maxLines` or `wrap: false`

Seen here a tooltip on the "Too long Agenda Event T..." would improve the user experience.

![image](https://user-images.githubusercontent.com/1432195/43973622-e8ac6682-9c8c-11e8-973f-e3a53fed0290.png)

Doesn't require schema changes, if we're agreed on this desired behavior, **open question** is simply how feasible this is on all renderers.

**Comment by dclaux** [comment]
It's a good idea, but the problem is that the truncation is done by the layout engine (the browser for HTML), and as far as I know there is no other way to determine whether the truncation did happened than to:
- Render the TextBlock without applying truncation
- Render the TextBlock with truncation applied
- Get the resulting bounding boxes of both and compare them

This is a very expensive process that would significantly impact performance, especially on Edge where getBoundingClientRect is significantly slower than in other browsers.

**Comment by andrewleader** [comment]
Proposal needs more investigation. Concerns about high cost of achieving this on HTML given that there's seemingly no way to create a text tip that only appears when the text is trimmed (potentially same concerns in UWP, etc)

**Comment by v-kydela** [comment]
Rather than having tooltips depend on how the HTML is rendered, could we perhaps give elements a tooltip property that allows for explicitly-defined tooltips?

**Comment by dclaux** [comment]
@v-kydela that is definitely possible and easy. But the drawback is that a tooltip might for an otherwise complete, non truncated piece of text, and thus be redundant.

**Comment by kahopkin** [comment]
@dclaux: it would be better to have some redundancy than not being able to show the full text at all.  Right now we don't have control where the text gets truncated and also no way of showing the full text, which kind of makes it not user friendly. How am I supposed to show the full text for like a title element in the card?  It is a basic html property, easily done in javascript also, but not with adaptive cards which makes it a drawback in a lot of scenarios.

Being able to add a tooltip property to all elements should definitely be implemented and offered for adaptive cards.

> @v-kydela that is definitely possible and easy. But the drawback is that a tooltip might for an otherwise complete, non truncated piece of text, and thus be redundant.

**Comment by paulcam206** [comment]
Not currently under consideration, but will reactivate should we decide to pursue.

**Comment by hulin17** [comment]
I think ToolTip has another function that it can be used to tell end-users an element can be clicked when users hover over the element. I noticed there is not a function like hovering over element to remind users to know what the element is used for. So if  there are too many "Clicked elements", tooltip or hovering function is necessary. Otherwise users maybe feel confused.
