### ISSUE TITLE
[UWP] Calling RenderAdaptiveCard more than once after setting a HostConfig property causes AccessViolation

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/AdaptiveCards#1806]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Author or host

Author, using UWP Lib.

# Version of SDK

NuGet 1.0.1

# Issue
I'm changing a property on my renderer's hostconfig:

    _renderer.HostConfig.Actions.ShowCard.ActionMode = ActionMode.Popup;

After I do this, if I call `RenderAdaptiveCard` on this renderer instance more than once I receive an access violation:

```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

If I remove the HostConfig line, it works fine calling it multiple times.

**Comment by andrewleader** [comment]
Interesting bug, which brings up some interesting questions...

1. Once a card is rendered with a specific HostConfig, what should happen if properties on that HostConfig change?
   1. Should that already-rendered card update? We don't today.
   2. Or should the already-rendered card always use the previous HostConfig?
      1. This is what we seem to do today, although that seems like it's just by chance. For example, for inline show cards, today we pre-render it... but if we changed the implementation to render the show card on-demand (when clicked), if the host config changed during that time, we would likely render the show card using the new host config, which technically would be incorrect.
   3. Or should we dis-allow changing properties of the HostConfig once it has been created, and instead require the host to create a new one (thus existing HostConfigs for existing cards can't be changed)

@michael-hawker what's the impact of this bug on your product? Can you work around it by simply creating a new HostConfig rather than changing properties on the existing HostConfig? Or does that also throw an exception?

**Comment by michael-hawker** [comment]
@andrewleader I was creating a component to re-render the adaptivecard as some source json changed.  It may not be that common I guess, but I worked around it for now by recreating the renderer instance.  I was hoping to re-use it as needed.

I didn't create my own HostConfig object, just setting the one created on the renderer.  I can try using a custom HostConfig object and see what happens.

In regards to your questions; I think I would expect scenario 2.  Since the renderer is returning an element object.  I wouldn't expect anything I do to the renderer after calling `RenderAdaptiveCard` to have an effect on the element I've already received.  Anything I change after should only effect the next call I make to `RenderAdaptiveCard`. (as you point out the system rerenders for showing a card on demand, so that's could be a bit strange).

I look at `RenderAdaptiveCard` as I do `XamlReader.Load`.  After I've called the method and get my object, I can recall Load on something else, but I wouldn't expect it to change anythign on my original object I got.
