### ISSUE TITLE
"type" field in element should be a required field

### ISSUE THREAD

**Issue by siduppal** [Microsoft/AdaptiveCards#1857]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host

Host

If you're an author, who are you sending cards to?

# Issue

"type" is NOT marked as required in the schema, but in reality hosts need to know the type of the element, e.g. "TextBlock", "Action.OpenUrl", etc. to know which other properties to parse for so the element can be rendered properly. Please update the documentation to mark "type" as Required = "Yes" everywhere.

**Comment by andrewleader** [comment]
Note that this is specifically about the documentation on the docs site: https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/card-schema#schema-container

The [schema explorer](http://adaptivecards.io/explorer/) already has these marked required. We probably should just replace one with the other, so that we don't have two duplicated sections where we document the schema.

**Comment by paulcam206** [comment]
This is fixed in f0772453dbdbf0ec06077676640fe2b33c62775d (mahiding/site1.1) which should be merged in shortly.
