### ISSUE TITLE
WPF textblocks texts doesn't wrap around when adaptive card added to WPF UI

### ISSUE THREAD

**Issue by vishaltmsft** [Microsoft/AdaptiveCards#1861]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* .NET WPF

# Author or host
Author

# If you're an author, who are you sending cards to?
Bing VisualSearch service sending cards to WPF clients (SDK Samples). 

# Version of SDK
latest master

# Issue
Same JSON renders perfectly in HTML host but the wrap setting doesn't take effect for WPF renderer. Attached is the adaptive card json. Tested and confirm this on the "AdaptiveCards.Samples.WPFVisualizer" as well. In my app the AdaptiveCard is hosted in ContentControl. It seems that Width of all the UIElements of the AdaptiveCard framework element returned by the API is set to Auto causing the wraping to not happen.

[adaptivecard.json.txt](https://github.com/Microsoft/AdaptiveCards/files/2354807/adaptivecard.json.txt)

**Comment by khouzam** [comment]
Thanks for reporting this. It also seem to affect the UWP renderer.

**Comment by vishaltmsft** [comment]
Hi @khouzam
Your workaround helped! In my case, I am programmatically transforming my json to adpativecards json. Using width:"1" worked. But I do have some difficulty with interpreting the width property. "auto" seems to be like magic but I think you described above how its interpreted differently on HTML/WPF. The doc says use a number but doesn't say with it means (i.e. is fraction between 0-1, a % between 0-100 or pixels). It seems, based on your explanation it is supposed be a float between 0-1. I wonder if you could update the doc + sample for **width** property on http://adaptivecards.io/explorer/Column.html, it would be great. 

Thanks for suggesting the workaround!

**Comment by dclaux** [comment]
The expected behavior when using **auto** columns is:
- An auto column requested width is whatever its content needs
- All auto columns are constrained by the available horizontal space
- An auto column might not get as much space as it needs if there isn't enough horizontal space left
- If multiple auto columns are competing for space, they each get their allotted space reduced proportionally to the total space they would need to completely fit their content

In this particular example:
- The card is 792 pixels wide
- The image in size medium seems to needs approximately 72 pixels (at 96 dpi)
- The longest TextBlock seems to need 20 times more space, e.g. 72 x 20 = 1440
- So the image column represents ~5% of the total width, and the text column represents ~95%
- So the image column gets ~40 pixels (5% of 792), and the text column gets ~752 pixels

IMO that should be the algorithm used in all renderers.

In this example, if the goal is for the image to not be shrunk, the solution is to set the width of the text column to **stretch** which essentially means "use whatever space is left after the other column got what it needs."

As for column widths expressed as numbers, the number can be any positive integer > 1. It represents the relative weight of the column within the set. For instance, say you have three columns with their weights set to 2, 7 and 5; respectively, they will get 14.3%, 50% and 35.7% of the available space.
