### ISSUE TITLE
Implement card view height calculation at the point that ACRRender.render returns

### ISSUE THREAD

**Issue by Pepsi1x1** [microsoft/AdaptiveCards#1925]
# Platform

* iOS

# Host

# Version of SDK

latest master

# Issue

CGSize for cards is not calculated (this is calculated on other platforms), this presents an issue particularly when cards have an input choice set. Width is provided as we initialise that at the ACRRender.render() call, but not height.

Integrating adaptive cards within MessageKit means that the cards are added to a cell within a collection view, this presents an issue that the height required for the containing cell cannot be calculated ahead of rendering the card as MessageKit requires implementing a cell size calculator in order to support os versions pre-ios 11.

**Comment by nesalang** [comment]
AdaptiveCards use autolayout. Height won't be known until layout engine resolves the constraints. Since MessageKit uses UICollectionView, you might want to override layoutsubview of ACRView (what is returned when you call "render") and have adaptivecards to send notification to update height. Another option is rendering AdaptiveCards as ViewController and override viewWillAppear method. 
AdaptiveCards can render either UIView or UIViewController.

Once height is received through above notifications, depending on how MessageKit uses its cell size calculator, you might have to call one of view refreshing APIs such as setNeedLayout on MessageKit's view or you could simply update the height value in the cell size calculator.

**Comment by jonmill** [comment]
Closed per above comment
