### ISSUE TITLE
Need a way to provide custom delegates for gestures in adaptive card

### ISSUE THREAD

**Issue by Aditya0603** [microsoft/AdaptiveCards#2122]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host

# Version of SDK

1.0.3 & 1.1

# Issue

In ACRLongPressGestureRecognizerFactory the long Press Gestures which are added, the delegate 
for them is set to an object of  ACRLongPressGestureRecognizerEventHandler, which also has the target Action for the gesture.

We need a way to set our class as the delegate to the gesture as the gesture delegate method  shouldRequireFailureOfGestureRecognizer implemented in ACRLongPressGestureRecognizerEventHandler always returns YES and waits for all other gestures to fail and then only call the gesture action.

But in a scenario where lets say we add the adaptive card to a view which has a long press gesture with default duration, a long press on the adaptive card will not call its action until the superview gesture has failed because of this delegate implementation.

So we need a way to set our class to become the gesture delegate so that priorities of gesture could be handled, the action target could remain to stay in ACRLongPressGestureRecognizerEventHandler.

**Comment by nesalang** [comment]
When there are competing event handlers, it is better to have logic that decides which handler to handle the event.  Even if Adaptive card's event handler is customizable and it handled the event. If the decision is not made, potentially more than one event handlers can handle the event at same time or different times.  Also, the adaptive card's delegate can't make the right decision since it doesn't have full context. So we suggest adding logic of deciding which handler to handle the touch event.
