### ISSUE TITLE
media does not show on the chat

### ISSUE THREAD

**Issue by maysamdabbagh** [microsoft/AdaptiveCards#2272]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

# Issue

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by maysamdabbagh** [comment]
I am trying the following sample adaptive card but when the bot return card it does not have the media and it just shows the action as shown in the image


![image](https://user-images.githubusercontent.com/19478671/50704517-44731700-101d-11e9-8e26-90ad80a63963.png)

{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "Media",
      "poster": "https://adaptivecards.io/content/poster-video.png",
      "altText": "Sample Alt Text",
      "sources": [
        {
          "mimeType": "video/mp4",
          "url": "https://adaptivecardsblob.blob.core.windows.net/assets/AdaptiveCardsOverviewVideo.mp4"
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "Action.OpenUrl"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}

**Comment by matthidinger** [comment]
Hi @maysamdabbagh, the Bot Framework WebChat control doesn't currently bundle the v1.1 release which is when Media was introduced. @compulim is it possible for him to replace the adaptive cards renderer lib in WebChat with the 1.1 build or does he have to wait until your next release?

**Comment by maysamdabbagh** [comment]
Hi  @compulim and @matthidinger 
Any update on this one?>

**Comment by compulim** [comment]
@corinagum Let's look at this one in our triage.

**Comment by corinagum** [comment]
Sorry for the delay in getting back to you! Had to learn a little about our upcoming release plans. 

Right now, it is not possible for @maysamdabbagh to update his Adaptive Cards library before we upgrade to Adaptive Cards 1.1.
Upgrading from v3 to v4 of Web Chat on Azure Portal for the embed story (@maysamdabbagh looks to be using v3 right now) is high on our priority list, and that item can be tracked here: https://github.com/Microsoft/BotFramework-WebChat/issues/1086. Once this item is complete, this will mean that all bots are able to use the latest Adaptive Cards release. 

[Upgrading to v4](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/01.c.getting-started-migration) by using the CDN or NPM method (and using the v4 development build of Web Chat) will allow users to use the updated Adaptive Cards library immediately. 

As for choosing your own Adaptive Cards library, for those who are using CDN or NPM, updating to v4 will eventually allow users to use their preferred version of Adaptive Cards, with the library being used as a component instead of part of the bundle. That issue can be tracked in https://github.com/Microsoft/BotFramework-WebChat/issues/1558. This will probably not be implemented before 1086, but in case you are interested please feel free to track that issue.
