### ISSUE TITLE
[UWP] Test app throw access violation when running

### ISSUE THREAD

**Issue by RebeccaAnne** [Microsoft/AdaptiveCards#2341]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Issue

Test app throws Access Violation

**Comment by RebeccaAnne** [comment]
Introduced by change #2191

**Comment by almedina-ms** [comment]
The issue comes from passing **strongThis** to the callback from the RandomAccessStream completed event, it looks like that variable was added in one of the first commits made in this repository but we have never used it, does someone knows why does it exist? Or why it loses it's reference if it does nothing ever @RebeccaAnne @paulcam206 @khouzam
