### ISSUE TITLE
Rendering Adaptive Cards to an image in .NET Core

### ISSUE THREAD

**Issue by GeorgeFrost** [Microsoft/AdaptiveCards#2449]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Author or host

Host

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

AdaptiveCards.Rendering.Wpf -Version 1.1.2	

# Issue

We want to render Adaptive Cards to an image inside a .NET Core Azure Function (V2) but the WPF package requires .NET Framework. Is there a version of the image renderer that doesn't take a dependency on WPF and therefore require .NET Framework?

**Comment by matthidinger** [comment]
Hi @GeorgeFrost, unfortunately we rely on WPF to handle the layout, which as of today requires the .NET Framework. That said, [.NET Core 3 is going to support WPF applications](https://devblogs.microsoft.com/dotnet/net-core-3-and-support-for-windows-desktop-applications/), which means we can add a .NET Core version of the WPF renderer and it **may** work in .NET Core Azure Functions. Unfortunately I won't know for sure until that day comes, since we had a bit of weirdness running WPF in Azure before, so it's hard to say if it will be a supported scenario.

As another option, issue #968 talks about a means of using the JavaScript renderer, along with a 3rd party headless DOM, which could be used to render an image from the cloud. 

If you dive into either of these topics and learn more, or have more questions, please do share.

**Comment by mattlpage** [comment]
Any updates to this issue?  I want to render adaptive cards as images in a aspnet core 5 application.
