### ISSUE TITLE
Custom Actions in adaptive card

### ISSUE THREAD

**Issue by pvmraghunandan** [microsoft/AdaptiveCards#2696]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* JavaScript

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?

If you're an author, who are you sending cards to?

We are using Direct Line and Web Chat as of now and custom channel for In Car

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

# Issue

As part of requirements, we need to send some actions to the car to do Phone call, Navigate to specific place. In order to achieve that, we would like to introduce custom Action Type as per  format below so that we can transform accordingly in our custom in car adapter. But, with this change, other channels like Web chat are breaking with error due to unsupported action types. How do we extend/ support custom action types for the adaptive cards?

**Note:** There is text and speak inside action also as we are thinking to them as hint to in car to speak when it is performing action.

```{
	"type": "AdaptiveCard",
	"version": "1.0",
	"id": "Actions",
	"speak": "Ok. Let me make sure I have this right, you want me to make a reservation for 6 people at a Italian restaurant for tomorrow starting at 8:00 PM. Is this correct?",
	"body": [{
		"type": "Container",
		"items": [{
				"type": "TextBlock",
				"size": "medium",
				"text": "Reservation request summary:",
				"wrap": true
			},
			{
				"type": "FactSet",
				"facts": [{
						"title": "Food type:",
						"value": "Italian"
					},
					{
						"title": "Date:",
						"value": "9/7/2018"
					},
					{
						"title": "Time:",
						"value": "8:00 PM"
					},
					{
						"title": "For:",
						"value": "6"
					},
					{
						"title": "",
						"value": ""
					}
				]
			},
			{
				"type": "TextBlock",
				"text": "Did I get it right?",
				"wrap": true
			}
		]
	}],
	"actions": [{
		"type": "Action.PhoneCall",
		"values": [{
			"phoneNumber": "034234343453",
			"picture": "http://......",
			"text": "Marie restaurant"
		}],
		"speak": "I will call Marie restaurant",
		"text": "I will call Marie restaurant"
	}]
}```

**Comment by BalajiR** [comment]
Have this custom action registered ?

*Example :*
‘Adaptive.AdaptiveCard.actionTypeRegistry.registerType("Action.Alert", () => { return new AlertAction(); });’

**Comment by pvmraghunandan** [comment]
We are planning to convert into custom logic during our transformation but in web chat, do we need to explicity register? If so, does the attached format works?

**Comment by BalajiR** [comment]
In order to aware of custom `element and action types`, the client side AdaptiveCard parser should know about the such custom type and its respective implementation.
You can find details and examples on this here,
https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/extensibility

**Comment by pvmraghunandan** [comment]
Does this apply even for other channels like Skype?

**Comment by shalinijoshi19** [comment]
@pvmraghunandan thanks for your request and @BalajiR for helping with the response. @matthidinger / @andrewleader is this something better handled first by the bot team?

**Comment by andrewleader** [comment]
@pvmraghunandan, Skype doesn't support Adaptive Cards, so the Adaptive Card itself won't be used there anyways.

But for other channels that you don't own (like Teams), your custom action will not work. The custom action *should* just be dropped, and the rest of your card would be rendered. Are you seeing the entire card fail due to the inclusion of the Action.PhoneCall action you added? If so, let us know, that shouldn't be the case.

For WebChat, since you're hosting that WebChat control on your own page, you should be able to add the custom type as Balaji pointed out. Let us know if you have questions about that!

One last thing... we recommend calling your custom action something like "MyCompany.Action.PhoneCall", because in the future, Adaptive Cards itself might introduce a type called "Action.PhoneCall" but it might have a different schema than what your type does, and that'll make for some nasty conflicts in the future when you send your card to newer renderers.

**Comment by pvmraghunandan** [comment]
@andrewleader Atleast in web chat it failed completely but we haven't tested in other channels. We will have to give a try on implementing custom map in we chat.
