### ISSUE TITLE
Padding mismatch between TS and other renderers with container style

### ISSUE THREAD

**Issue by paulcam206** [Microsoft/AdaptiveCards#2782]
card:
```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "ColumnSet",
"style": "emphasis",
			"columns": [
				{
					"type": "Column",
					"width": "auto",
"style": "attention",
					"items": [
						{
							"type": "Image",
							"url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
							"size": "small",
							"style": "person"
						}
					]
				},
				{
					"type": "Column",
					"width": "stretch",
"style": "accent",
					"items": [
						{
							"type": "TextBlock",
							"text": "Matt Hidinger",
							"weight": "bolder",
							"wrap": true
						},
						{
							"type": "TextBlock",
							"spacing": "none",
							"text": "Created {{DATE(2017-02-14T06:08:39Z, SHORT)}}",
							"isSubtle": true,
							"wrap": true
						}
					]
				}
			]
		}
	]
}
```

WPF:
![image](https://user-images.githubusercontent.com/16614499/56839638-4ebd5900-6838-11e9-831e-e4d493e67733.png)
UWP:
![image](https://user-images.githubusercontent.com/16614499/56839657-6399ec80-6838-11e9-8de8-3a14c5d45c41.png)
TS:
![image](https://user-images.githubusercontent.com/16614499/56839663-70b6db80-6838-11e9-8eec-84f0330d246f.png)

Typescript appears to be applying bleed?

**Comment by dclaux** [comment]
The TS screenshot was taken from the designer which reserves additional space top and bottom to facilitate drag/drop. The designer should not be used as the reference. The correct rendered layout in the visualizer is this:

![image](https://user-images.githubusercontent.com/1334689/56840604-41ef3400-683d-11e9-92c0-50412931f7f1.png)

(note I used emphasis everywhere instead of "attention" and "accent", but the result is the same)

TS is correct given our recent decision to always bleed columns.

**Comment by dclaux** [comment]
Didn't mean to close - WPF and UWP should be update, unless we change our mind wrt column bleeding.

**Comment by RebeccaAnne** [comment]
We did change our mind with respect to column bleeding, and it looks like all renderers are consistent now (don't apply bleeding). Closing.
