### ISSUE TITLE
[minHeight] Container with only background image without minHeight property is rendered inconsistently today

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#2785]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF
* JavaScript
* UWP

# Version of SDK
master

# Issue
This json below *without* any minHeight specified, actually renders with a default size in the JS designer, but will not render at all (interpreted as an empty container) on UWP/.NET. The spec is unclear on what this should be interpreted as at this point.

The behavior that JS defaults to today - ie a default minHeight value seems to be more intuitive to me

(See also example in dup'd bug #5453)

```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.1",
  "body": [
    {
            "type": "Container",
            "backgroundImage": {
              "url": "https://picsum.photos/300/400?image=882"
            }
        }
  ]
}
```

## Decision

The behavior for an empty container (with `style`) seems to be that it receives its padding and is inserted. **Same behavior should be done with `backgroundImage`... it introduces padding, and therefore gets some sort of height, and so the image shows up slightly, just like JS does**

**Comment by shalinijoshi19** [comment]
@andrewleader FYI..

**Comment by andrewleader** [comment]
So, important clarification... it seems JS isn't using a "default minHeight", it's simply applying the padding.

![image](https://user-images.githubusercontent.com/13246069/58047039-e9d5e580-7afb-11e9-979a-6fc66d5f8f95.png)

```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.1",
  "body": [
        {
            "type": "TextBlock",
            "text": "Empty container with background image"
        },
    {
            "type": "Container",
            "backgroundImage": {
              "url": "https://picsum.photos/300/400?image=882"
            }
        },
        {
            "type": "TextBlock",
            "text": "Empty container with emphasis"
        },
        {
            "type": "Container",
            "style": "emphasis"
        }
  ]
}
```


Both assigning a different style or adding a background image introduces padding to the container. That padding results in the "default minHeight", but the key distinction there is that the default minHeight will be different depending on the host config (since it's based on the padding, which hosts pick).

**WPF Visualizer**

![image](https://user-images.githubusercontent.com/13246069/58047127-33263500-7afc-11e9-8c57-f14cbae6ac8a.png)

**UWP Visualizer** (ignore incorrect height of background image, separate bug)

![image](https://user-images.githubusercontent.com/13246069/58047169-4cc77c80-7afc-11e9-8538-79ea5c50d57d.png)

**Android visualizer**

Same as UWP


The behavior for an empty container (with `style`) seems to be that it receives its padding and is inserted. **Same behavior should be done with `backgroundImage`... it introduces padding, and therefore gets some sort of height, and so the image shows up slightly, just like JS does**

**Comment by golddove** [comment]
Should check other platforms, too

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
