### ISSUE TITLE
[iOS] GIF support in images

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2876]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

iOS implementation of #3079

**Comment by andrewleader** [comment]
We need to check iOS and see whether it does or doesn't support GIFs

**Comment by Sujit-Gaikwad** [comment]
hi as we got support for GIF image on Android and desktop teams. but iOS devices having this issue. are Microsoft teams going to consider this feature?

**Comment by Sujit-Gaikwad** [comment]
Hi,
I found this issue link under the adaptive card roadmap page.
can you please update me that for iOS is it going to take forward because as per my knowledge except iOS other MSTeams platform supporting this image format. 
In iOS teams. the image format is supported but the **displayed animated image is not working it is getting displayed in normal image form**.

**Comment by ijennykim2** [comment]
Any updates on this?
