### ISSUE TITLE
Universal action model SDKs

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#3076]
# Summary

Today, there's no way to author a single interactive card that you can send to multiple hosts and have it work. You have to do special work for each host to handle the action callbacks, and they're all handled differently. In Outlook, you use `Action.Http` and it calls back to your server, in Teams you use `Action.Submit` and it calls back to your bot, in other hosts you also might use `Action.Submit` but it'll call back to a different endpoint...

# Requirements

- P0: Authors can provide an action that calls back to their server with the input data

- P0: Authors can respond with an updated card

- P0: That update is somehow broadcasted to all instances of the card

  - For example, if I approve an expense report from within Teams in a card on my desktop, and it responds back updating the card saying it's approved, when I open Teams on my phone, I should also see that it's been approved.

- P0: The callback to the author's server is secure and safe

- P1: There's a universal way for authors to validate what host the action came from

# Spec/schema

After the proposal process, update this with a link to the spec PR.

# Proposed changes

## Authentication

Short-term single-use auth access tokens is the way to go. That's what AMP uses for interactive emails: <https://developers.google.com/gmail/ampemail/authenticating-requests>

On top of that, we could add a unified way of validating the host and the user, for those who want to make their content even more secure (although note that that would then somewhat defeat the purpose of the universal action, as it's now limited to a specific host). But it'd still be better than today, with one single generic way to do anything.

## Updating everywhere

Updating the card everywhere is the tricky part. If the HTTP request simply goes directly from the Adaptive Card SDK to the author's server and back, that instance of the card has no way of updating within Teams itself.

### Solution 1: Refresh/live cards

We could have cards be loaded from URLs, so that every time the card is opened, it asks for the latest card. Then developers also wouldn't have to worry about pushing updates to every host that they sent it to (Teams/Outlook/Bot Framework).

### Solution 2: Pass-through via host

The host can pass through and intercept the HTTP request and then be sure to update the response everywhere. Note that if the author sent their card to two different hosts, the author would still have to make sure to push updates to those other hosts.

# Example

Provide an example payload

# Host Config

Quickly describe changes to the host config, if any.

# Down-level impact

Describe how down-level is impacted for authors.

# Host burden

Describe the burden hosts have when we introduce this feature. For example, are they going to have to add something new to their host config or native styling as a result of a new element we're adding? Are there breaking API changes that hosts have to use? Are we deprecating something from host config that could cause potential confusion?

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/1711647

**Comment by andrewleader** [comment]
# Universal actions meeting 6/25/2019

David: Should we deprecate existing non-universal actions and force convergence, or add a converged option without deprecating the propriatary ways?


Vinay: In Teams, today we replace the card, but depending on the requirement, they might want to show a new card rather than replace the old card

Bill: I look at formalizing authentication, retry, there are a lot of things that are host specific when you talk about HTTP. I look at it as having an Action.Submit semantics and we can see how those semantics map to a protocol. At the end of the day, there's Action.Http which is tied to a protocol, vs Action.Submit is underspecified and not tied to a protocol. I was think of coming up an Action.Submit that's protocol and host independent and wouldn't necessarily assume HTTP.

David: How do you suggest we do that? Would we add explicit channels?

Bill: I guess, I mean I think what you alluded to, potentially. I think we're thinking about the protocol a bit too much, how do you standardize the payloads of the data, like for example on Skype chat service, they do fairly deep protocol inspection.

Dan: We had to solve a similar problem in Bot Framework, we had fragmentation around postBack/imBack, best way to satisfy developer need was to create really predictable semantics across the board. As the hosts varied in capabilities, you'd have a graceful fallback. You'd code in the most elegant that you want and then the degredation would still give you what you'd want. We've talked about actions that go back to the app. What do we think about actions that go back to the client, like open URL and invoking add-ins?

David: That's the next set of problems, I refer to those as native actions vs external actions.

Dan: I'm looking for both items and having an understanding of how we support uneven capabilities across the board is important. The thing we're missing today is how you can compose those together in a way that's clean. Establishing that will get us to a point where if you know phone call is supported, you can take advantage of that.

Vinay: Kaizala have discussed some of these things and we'll need native actions too. But first solve the first problem of converging the external actions.

David: Victor's opinion was that the only action we needed was OpenUrl for native actions, and each of those could be a protocol like newmail:aleader@microsoft.com

David: I was talking about fallback eariler, which works on actions too. What if we said authors just have to use fallback everywhere to implement on each host?

Andrew: But then authors would have to design specifically for each host, thus making it no longer universal

Vinay: Many first party apps would worry about opening so many HTTP connections to third party services, like Teams has a lot of concerns about hitting all these services.

Andrew: That's accomplishable if you simply call back to a Teams server and then the Teams server hits the third party

Bill: HTTP has issues, it sounds easy but in practice it can be narly

Dan: It's okay if some features aren't available everywhere, as long as things are predictable. 

David: As an author, if I went to add actions, how do I learn what I use to make my card work everywhere?

Dan: There's cases where cards are used within an SDK, the docs for the card aren't just about the card, it's also how actions influence the conversation state in the bot

Dan: My pri 0 is predictability for the developer, that materializes as a set of practical tradeoffs, I'm happy to hold off on that until we have some concrete details and then see how those apply.

Bill: What if we thought about it as a reliable HTTP delivery service, where host just calls it and the service handles delivery. Outlook has that middle tier that appends the token and whatnot. What if we made that universal?

Dan: There's three things our framework has, the area I see value is in the syntax mapping.

David: Can you send a description of that Dan within a week?

Andrew: We should ensure our model works for external third parties too, so if other chat apps adopt Adaptive Cards, authors can write a universal card that works everywhere, not just within Microsoft
