### ISSUE TITLE
Inconsistent rendering of Adaptive Cards across ecosphere

### ISSUE THREAD

**Issue by morgangraphics** [microsoft/AdaptiveCards#3098]
# Platform

What platform is your issue or question related to? (Delete other platforms).

Teams

# Author or host

I am sending the JSON object/output from the [Designer for Actionable Messages](https://amdesigner.azurewebsites.net/) to a Teams Incoming Webhook connector.  While the designer shows how the Card is supposed to look as intended

![Designer](https://user-images.githubusercontent.com/607594/59882958-a502d000-9381-11e9-9bf7-8c2fe7904e16.png)

The actual results in Teams looks like: 

![actual-results](https://user-images.githubusercontent.com/607594/59883206-4f7af300-9382-11e9-9889-0dda98ae1778.png)

Rendering only the Title and Text key/value pairs on the root of the JSON object.

Using the App Studio Card Designer renders the Card close to the Designer for Actionable Messages version

![app-studio](https://user-images.githubusercontent.com/607594/59882963-a7fdc080-9381-11e9-9f89-e37e232eefba.png)

Minus an image or two in the preview. However, when clicking the "Send this card to me" button, it renders

![teams](https://user-images.githubusercontent.com/607594/59882966-a9c78400-9381-11e9-86a0-fe8975edb19a.png)

Where things like height and width of images are not being respected if they even render at all. It should be noted that the validator for the App studio version of card builder complains on the output of the Designer for Actionable Messages

Valid in Designer for Actionable Messages UI
```
"actions": null,
"style": null,
"backgroundImage": null,
```

Only Valid in App Studio Card Designer
```
"actions": [],
"style": null,
"backgroundImage": "",
```

If you're an author, who are you sending cards to?

I'm sending cards to a channel in Teams using the Incoming Webhook connector

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

JSON Schema 

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "title": "ZAP Vulnerability Scan",
  "text": "ZAP Vulnerability Scan ##DATE##",
  "version": "1.0",
...
```

# Issue

See above

**Comment by andrewleader** [comment]
Hey @morgangraphics, thanks for posting. Teams is still using Adaptive Cards 1.0, which doesn't support `height` and `width` properties on images. You'll have to design your card avoiding the usage of any newer features for now.

Teams is working on updating to Adaptive 1.2 over the next few months. We'll notify you when they update!

We're also working on making the Designer only show properties that are available in that host's currently shipped version, so that when designing your card for Teams, you wouldn't see properties like height and width which aren't yet applicable to them.

Let us know if you have any other questions/issues/feedback! Thanks!
