### ISSUE TITLE
Deprecate AdaptiveCard style and HostConfig allowCustomStyle

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#3168]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Potentially everything

# Issue

.NET WPF doesn't support the "style" property on the card level, even when adaptiveCard.allowCustomStyle is set to true in the host config:

![image](https://user-images.githubusercontent.com/9091833/61006541-6bd5d400-a31f-11e9-9e6f-b109e6883813.png)
![image](https://user-images.githubusercontent.com/9091833/61006549-71cbb500-a31f-11e9-943b-cf930dc0045a.png)

Javascript for comparison:
![image](https://user-images.githubusercontent.com/9091833/61006590-8dcf5680-a31f-11e9-9878-b1e13e1e1540.png)

```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "style":"good",
    "body": [
        {
            "type": "TextBlock",
            "text": "New TextBlock"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}

**Comment by matthidinger** [comment]
@dclaux FYI I think we talked about this, Outlook was the only known host using custom styles and we never officially documented it. Since the same experience can be created using a Container with style and bleed, seems like we can remove this potential point of fragmentation between hosts. Let me know if you have any concerns I overlooked

**Comment by dclaux** [comment]
I can't really remove it unfortunately. I would run the risk of breaking existing Actionable Message scenarios.

**Comment by jonmill** [comment]
WPF is deprecated, closing
