### ISSUE TITLE
[SharedModel] Ambiguous behaviour for set column width

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3228]
# Platform

* Shared model

# Version of SDK

latest master

# Issue

There is no documentation for the expected behaviour on what happens if the pixel width is set after width in a column. The behaviour I would expect is for the last property set to be the one to be respected

Also, what's the expected behaviour if a column is set 0 as the pixel width? Should we respect that value or use Auto in that case?

@andrewleader , do you have any input?

**Comment by andrewleader** [comment]
Huh? There is no `Column.pixelWidth` property, only a single `width` property that takes either `auto`, `stretch`, a number, or `50px`, so there's no logic needed to determine which value to use, there's only one value ever.

![image](https://user-images.githubusercontent.com/13246069/61234696-9db4b500-a6e8-11e9-836e-ba6031ca5d6b.png)

I think the shared model **added** a concept of two properties (since they're of different type). So I imagine the shared model populates the PixelWidth property if `width` was set to a pixel value, or populates the Width property if `width` was set to `auto`, `stretch`, or a number.

So I'm guessing as a consumer of the shared model, if PixelWidth is specified, you always use that, but maybe @paulcam206 would know how the shared model implemented this

**Behavior of 0 pixel width:** In the 7/12/2019 meeting, we decided respect the value as-is... make the column 0 pixels wide (but still have the left/right padding around the column and adjacent columns)

**Comment by paulcam206** [comment]
The shared model only serializes/deserializes the string `width` value. When a string width is set, under the hood, the value is parsed and the internal pixel width is set. We don't reference the pixel width when serializing. However, this does bring up an interesting quirk: if someone calls `SetPixelWidth()` *after* a width has been set (either via a json property or the object model), the column will display using the supplied pixel width, but serialize with the string width.

**Comment by dclaux** [comment]
The rule should be that if pixel width is set in the OM it wins. That's what JS does.

**Comment by paulcam206** [comment]
I don't disagree with that.

What I'm saying is that in the shared model, if you `column->SetWidth("40px");`, then `column->SetPixelWidth("5px");`, and then `column->GetWidth(&someString);`, `someString` will be `"40px"`, even though `column->GetPixelWidth();` will return `5`.

This is a bug :)

**Comment by shalinijoshi19** [comment]
Ok so catching up on this, @paulcam206, looks like there's fixes needed in sharedmodel then here? Assigning to you for fixing.  Thanks!
