### ISSUE TITLE
Insecure Randomness

### ISSUE THREAD

**Issue by mikesorsibin** [microsoft/AdaptiveCards#3243]
In adaptivecards.js, When scanned on fortify, we are encountering an error stating Insecure Randomness on the line Math.Random()
Insecure randomness errors occur when a function that can produce predictable values is used as a source of randomness in security-sensitive context.
Please help us solve the issue.

**Comment by shalinijoshi19** [comment]
Thanks for reporting @mikesorsibin. We'll make sure we fix this for our next outbound release.

**Comment by shalinijoshi19** [comment]
@paulcam206 mind taking a stab at this ? Should be straightforward I am hoping and probably a matter of seeing Random() in the constructor say with a time-based (ticks are classic i think) seed

**Comment by paulcam206** [comment]
These numbers are used to generate unique IDs for elements rendered on a page. However, we don't need cryptographically strong numbers here. The IDs are ephemeral and only need to be unique to a single card render. The threats as I see them would be:
* ID collision in generated elements - should be very rare. this would require two elements to get the exact same numbers from four consecutive calls to `Math.Random()`. 
* Script could guess the ID of a generated card element - doesn't seem likely. even in the event that script *could* guess, it's unclear that the implications are in any way scary. it would require a malicious actor to already have script running with access to the DOM. if this were the case, guessing the ID ahead of time doesn't seem to provide any value, since the script could simply inspect the DOM without using the ID.

**Comment by paulcam206** [comment]
oops! reopening :)

**Comment by shalinijoshi19** [comment]
@mikesorsibin could you please take a look at @paulcam206 's response above ? We aren't using Random() in a security context here rather just to generate identifiers for AC elements... Could you elaborate a bit on the "fortify" tool and your scenario here please that is blocking you? Thanks!

**Comment by shalinijoshi19** [comment]
Actually us switching to leveraging node-uuid should address this and get rid of the custom code off of stackoverflow with potential issues ; FYI @dclaux  this is coming from our code that we've chosen to pull in to implement UUIDs ourselves here UUID::generate().

**Comment by dclaux** [comment]
FYI it makes no sense for the JS renderer to take a dependency on that 12 KB library. The current UUID code in JS takes < 1000 bytes and is completely sufficient given how it is used, namely to generate locally unique ids to group check boxes and radio buttons.
