### ISSUE TITLE
The Adaptive cards designer let you create adaptive cards version 1.2 but with version tag 1.0

### ISSUE THREAD

**Issue by EkimoCode** [microsoft/AdaptiveCards#3335]
The designer let you add new elements like ActionSet while leaving the version tag on "1.0".
(Moreover, it would be amazing to be able to design adaptive cards by selecting the version and so be able to add only elements available on that version).

**Comment by dclaux** [comment]
That is by design. You can include 1.2 elements in a 1.0 card so as to make it possible for a host that only supports 1.0 to still render it minus the 1.2-specific features.

There could however (and there will be) an easier way to set the card version (better than having to set it in the JSON editor)
