### ISSUE TITLE
[iOS][Extending renderer] [TextBlock renderer crashes when extended]

### ISSUE THREAD

**Issue by Jenna-Premera** [microsoft/AdaptiveCards#3456]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Author/host, Premera app

# Version of SDK

1.2.2

# Details

I am trying to add custom styling to card elements. For action elements, your examples indicate I need to call your render function from mine, and then I can apply my custom styling to the generated UIKit controls. However, if I do the same for static elements your render function crashes. This is due to logic in ACRView.addTasksToConcurrentQueue which decides to bypass logic that the stock renderer relies on, whenever the renderer is overridden.

To work around this, I have to implement a render function in Objective C++ and implement the renderer in its entirety, the exact opposite of the pattern for an action element. This also limits the pool of developers who can work on this (many newer developers have only used Swift), and making adoption of Adaptive cards less attractive to iOS developers.

**Comment by nesalang** [comment]
The reason for the crash is analyzed and well understood.
-	Client wants to use default text renderer in the context of its custom text renderer.
-	This scenario should work, but the issue was iOS renders runs text processing tasks in parallel, and prevent custom renderers from running in its async parallel task queue, so the intermediate result would not be available down the stream. Bug was introduced, and it seemed to remove the code handling this case
The current state:
- Jenna, from Primera knows the workaround which is allowing the custom renderer to run in async queue. This is safe for this particular use case since in reality the renderer in async queue is default renderer.
- Proper fix will be provided, and meanwhile Jenna's shortcut will unblock the current work
- Goal is once the proper fix is added, Jenna will not notice any differences. 

Another concern from Jenna is Swift.
- Jenna likes to have iOS renderers in Swift. Our library can be used in swift with bridge header.  But being able to market the renderer as written in Swift could bring more developers. 
Swift UI
- Swift UI only support iOS 13. Swfit UI can’t support iOS 12 which should be supported for some time, and iOS 13 hasn’t released, yet. So right now transitioning into Swift UI doesn’t make sense.
