### ISSUE TITLE
[Shared] ActionSet::m_orientation unused

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3461]
Looks like `ActionSet`'s `m_orientation` member is initialized, but not referenced (introduced in 393d1b0a5ac8dc62c1b750c8f643848753b31048).

Declared:
https://github.com/microsoft/AdaptiveCards/blob/302b0d8a397ef46fce1f80c73ff73253ba05397e/source/shared/cpp/ObjectModel/ActionSet.h#L12-L29

Only use:
https://github.com/microsoft/AdaptiveCards/blob/302b0d8a397ef46fce1f80c73ff73253ba05397e/source/shared/cpp/ObjectModel/ActionSet.cpp#L11-L20

**Comment by paulcam206** [comment]
Assumption is that there's either some missing feature work here, or we can just get rid of the unused member...

**Comment by dclaux** [comment]
ActionSet has an orientation property in JS allowing card authors to pick horizontal vs. vertical layout, overriding HostConfig. In many cases, horizontal orientation might be what works best at the card level, but not within a column.

**Comment by paulcam206** [comment]
Makes sense. As implemented here, it's a set-only property :)

**Comment by shalinijoshi19** [comment]
@Paulcam206 what is the proposal here with this issue?

**Comment by RebeccaAnne** [comment]
@shalinjoshi19 The story here is that this member variable exists but is not hooked up to anything. It would in theory be in support of an orientation property on ActionSet. That is not an officially documented feature, but per David's comment it already exists on JavaScript. 

The proposal would be to either document and implement orientation for ActionSet on all non-JavaScript platforms, or otherwise to remove this stray variable that's not doing anything.

**Comment by paulcam206** [comment]
This code has been removed for now. However, I'm leaving this issue open to track the possibility of eventually adding this functionality back in :)
