### ISSUE TITLE
[iOS][Custom Actions] Support custom action parsing for selectAction

### ISSUE THREAD

**Issue by tnev** [microsoft/AdaptiveCards#3519]
# Platform

* iOS

# Author or host

host

# Version of SDK

1.2.1

# Details

It doesn't currently seem possible to use custom actions for a Container's `selectAction`. It looks like selectAction uses `ParseContext`'s `actionParserRegistration` to look for action parsers corresponding to the action type, unlike the `ACRCustomActionRenderer`, which will call `ACRRegistration`. I'm not sure how we could override the `selectAction` parsing unless it used ACRRegistration as some point. Could you confirm this, or let me know if there's an alternative for what I'm trying to accomplish? Thank you.

**Comment by shalinijoshi19** [comment]
@nesalang thoughts ?

**Comment by nesalang** [comment]
@tnev @shalinijoshi19 
Hello,
we can add this feature to iOS. basically, it will allow registering custom targets for actions. action rendering involves creating button and adding the targets. Since SelectAction is adding the targets to existing UI elements such as UIImageView, current action renderer registration will not work and a new target registration is needed.   
And I could share a branch that has this feature if you are blocked, but I have to check to see if this feature is supported on all other platforms, and make sure the way we support is consistent across the platforms, so complete solution may come later, but the release of iOS solution won't be depended on implementation of other platforms just designs unless our team wants to time the releases as well. because of that reason, the change I share with you may change.
