### ISSUE TITLE
[JavaScript] Drag & drop of elements in designer is not working in Safari

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#3532]
# Platform

* JavaScript

# Author or host

Host Name : Microsoft Search

# Version of SDK

adaptivecards-designer@0.7.1

# Details

In `https://vnext.adaptivecards.io/designer/`(only for Safari) I am not able to drag and drop any card element into designer

**Comment by shalinijoshi19** [comment]
@dclaux could you help take a stab at this real quick? Also @atishayv is this only the vnext that you are seeing this behavior for or also adaptivecards.io/designer ?

**Comment by atishayv** [comment]
@shalinijoshi19  This is happening for adaptivecards.io/designer also

**Comment by dclaux** [comment]
This is due to how image fallback is handled. I can do better when the target image size is known in advance (like in this case) by showing a fixed placeholder. When "stretch" or "auto" are used the image size isn't known until the image has loaded, so I can't fully eliminate the flickering, but maybe I can reserve a minimum amount of space all the time, enough to show the fallback image.

**Comment by jonmill** [comment]
This should be fixed in the latest builds; please re-open if this is not the case and we'll re-engage. Thanks!
