### ISSUE TITLE
[JavaScript][The adaptive card flickers on changing text block value if there is an image url which is data binded in template]

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#3578]
# Platform

* JavaScript

# Author or host

Host Name : Microsoft Search

# Version of SDK

adaptivecards-designer@0.7.1

# Details

Go to : https://vnext.adaptivecards.io/designer/

Paste this in `Card Payload Editor` :

```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Publish Adaptive Card schema"
        },
        {
            "type": "Image",
            "style": "Person",
            "url": "{url}",
            "size": "Small"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

and paste this in `Sample Data editor` : 
```
{
    "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg"
}
```
In the unpreview mode, select the text block and change the `text` value of `TextBlock` in `Element Properties`. 
While typing the whole adaptive card will flicker.

**Comment by matthidinger** [comment]
Thanks for filing this!

@dclaux any thoughts here? As mentioned this long happens in non-preview mode, presumably since it tries to redownload an image that doesn't exist (and isn't even a valid URL). This actually points at something else, should we really show the sad face if the URL is data bound? I know the renderer doesn't explicitly know what templating is, but is there anything we can do to improve this experience at design time?

**Comment by dclaux** [comment]
I was certain I had posted a comment here... weird.

We have to show the sad face or a whatever placeholder, otherwise users might not even realize they have an empty image in their card.

We can improve the logic for when the placeholder is shown and how it is sized:
- We can always show a placeholder as the image loads, rather than only if the image fails to load
- If the image's "size" is specified, we can use that for the placeholder size
- If the image's both "width" and "height" properties are specified in pixels, we can use that
- Otherwise, we can use a default placeholder size

**Comment by jonmill** [comment]
This doesn't repro anymore...please re-open if you find this is not the case and we'll re-engage. Thanks!
