### ISSUE TITLE
[iOS]Background DataUri is not working

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3636]
# Platform

* iOS

# Version of SDK

Release 1.2 branch

# Details

The v1.1/Elements/AdaptiveCard.BackgroundImage.DataUri card does not render the background image. Other Data uri cards are able to show the pictures correctly.

**Comment by shalinijoshi19** [comment]
@nesalang assigning to you for investigation; Is this a regression with 1.2 then compared to 1.1 ? Is this going to affect the teams upgrade do we think?

**Comment by shalinijoshi19** [comment]
@nesalang, updates on this one?

**Comment by nesalang** [comment]
> @nesalang, updates on this one?

when notification for image loading done is arrived, a target view that will host the background image won't have dimension since data URI doesn't involve network and the image size is small; thus finishes instantly. We need to make adjustment in setting the layout constraint when missing height of the target view.
