### ISSUE TITLE
.io site needs Partners/Integration page showing AC support status

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#367]
Feedback from community, particularly bot developers, has been to include a list of channels and what level of adaptive cards is supported in them. 

Channel | Status
--------|-------
Emulator | Full support
WebChat | Full support
Skype | Full support coming soon
Microsoft Teams | Full support coming soon
Kik | Render to Image + limited mapping to  keyboard (full support coming)
Facebook Messenger | Render to image + limited mapping to  buttons
Slack|Render to Image + limited mapping to buttons
Telegram|Render to Image + limited mapping to keyboard
SMS | Image + text
GroupMe | Image + text
Email | Image + limited mapping to links
Bing | Coming soon via Skype Webchat Control
Cortana | not supported yet
Skype4B | Not supported

**Comment by nwhitmont** [comment]
Can confirm, this gets asked a lot.

**Comment by danmarshall** [comment]
For WebChat, we should say "Action.Http not supported"

**Comment by danmarshall** [comment]
Perhaps a third column for details?

**Comment by nwhitmont** [comment]
@matthidinger Have there been any recent changes to the channel support matrix since this was first posted? Specifically, Facebook Messenger support?

**Comment by nwhitmont** [comment]
@matthidinger Any update on getting this into the docs?

**Comment by qpongo** [comment]
Can I (or anyone) create some new issues like '**Skype Now Supported**' (or Beta) so that we can subscribe and come back once it's working?

_Someone commented in related repository that they felt that they got played.  Well, me too!

I just spent a week learning the tools, bought an Azure account (which I didn't have before), worked around all the bugs so that everything runs in the Channel Emulator / Dev Framework Test Page and was ready to publish a cool bot that I wanted to roll out next week - in 23 languages and 60+ countries.  All for NOT.  :(_

I would have done something else with my time if it was more clear that this framework didn't work.

**Comment by matthidinger** [comment]
Hey folks, I'm really sorry about the troubles here. I've migrated our content to Microsoft's official Docs platform, added a Bot tutorial and Channel Status, and added some more "Preview" disclaimers throughout the content.  

https://docs.microsoft.com/en-us/adaptive-cards/get-started/bots#channel-status

Still on the list is setting up a blog to subscribe to general announcements such as Skype support, etc. 

We very much appreciate your patience while we get things ramped up.

**Comment by bhashithahemantha** [comment]
@matthidinger  how can we use adaptive cards with microsoft teams?  is it supportive yet?

**Comment by e0003894** [comment]
Will there be a day where Facebook Messenger would fully support adaptive card?

**Comment by ImranJaved** [comment]
Hi,

There is similar thread on https://github.com/Microsoft/BotBuilder/issues/3015.
Is there any update for skype?

**Comment by andrewleader** [comment]
Closing as we have this on docs: https://docs.microsoft.com/en-us/adaptive-cards/resources/partners
