### ISSUE TITLE
[Javascript][Application (Author) Rendering] [Don't delete fields where the template doesn't resolve]

### ISSUE THREAD

**Issue by jpjpjp** [microsoft/AdaptiveCards#3681]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host

Author  -- sending cards to Webex Teams.

# Version of SDK

adaptivecards-templating@0.1.1-alpha.0

# Details

I'm using the JS Template SDK in my app to populate template cards with data before posting them (to Webex Teams in my case).    I've noticed that if I attempt to expand a template that does not define all of the "templatized" fields in my design the fields that are not populated are deleted.

As an alternative, perhaps the fields could be left unchanged?  In my case I actually do a second pass, and would like the fields that were not populated in the first pass to still remain so they can be exposed in the second pass.

As an example,  let's define a card with two templateized fields, but create a context that only satisfies one of them:

```js
let ACData = require("adaptivecards-templating");
let cardDesign = {...
  body [
   {
      "type": "TextBlock",
      "id": "{id}",
       "text": "{text}"
    }
  ]...
};
let  template = new ACData.Template(cardDesign);
let context = new ACData.EvaluationContext();
      context.$root = {
         id: "1234"
      };
let card = template.expand(context);
```

The resulting card will be:

```json
{...
  body [
   {
      "type": "TextBlock",
      "id": "1234"
    }
  ]...
};
```
Note the text field is eliminated (making this invalid according to the schema)

An alternative would be to leave it unchanged:
```json
{...
  body [
   {
      "type": "TextBlock",
      "id": "1234",
      "text": "{text}"
    }
  ]...
};
```
In this case if the card is rendered, it is quickly obvious what the problem is.   If the application performs multi-pass templating (as mine attempted to do), there are additional opportunities to expand the template before the render request.

**Comment by dclaux** [comment]
@jpjpjp thanks for this detailed feature request. This is a scenario we had not considered before. It's easy enough to allow it - @matthidinger what do you think?

**Comment by jpjpjp** [comment]
Curious what the removal of Triage Needed label means.  I may be a singleton but I do think allowing developers the choice of how to handle unresolved template values will ultimately drive a wider variety of solutions.

FWIW, in my case, I have a "build process" that creates the runtime versions of my cards based on the environment they are in.   As an example, in the build process I set the {cardSourceUrl} template in the url field  for the "Show this card's source" Action.OpenUrl.

At runtime when my app is running in a live chat session I might set update a url field with a template called {avatarUrl} with the avatar of the user that is actively interacting with my card.

**Comment by dclaux** [comment]
Adding "Triage Needed" back. This issue has not been discussed and no decision has been made as to whether we address it and how.

**Comment by shalinijoshi19** [comment]
@dclaux is sthis a bug or a feature request?

**Comment by shalinijoshi19** [comment]
@RebeccaAnne looks like another contender for the Wednesday discussions maybe? @matthidinger FYI.

**Comment by dclaux** [comment]
@shalinijoshi19 it is a feature request.

**Comment by shalinijoshi19** [comment]
@nesalang FYI as you ramp up on the templating story in general.

**Comment by nesalang** [comment]
@shalinijoshi19 
thanks for including me for the discussion. This is an interesting use case.

**Comment by dclaux** [comment]
@nesalang and @shalinijoshi19 the "problem" isn't so much with templating as it is with AC renderers.

Our design to this date has been that when the `"text"` property of a **TextBlock** isn't specified or is set to undefined or an empty string then the TextBlock isn't rendered. Therefore, if the `"text"` property is set to an expression (`"{text}"` in the above example) and that expression evaluates to undefined or an empty string, the TextBlock isn't rendered, and that's by design end-to-end.

We need to decide whether or not we want to revisit our design. If we do, then the right solution is to simply stop dropping TextBlock when text is not specified, set to undefined or an empty string.

**Comment by nesalang** [comment]
@dclaux 
When the expand operation is complete, do we have to leave the expanded text as a valid adaptive card? Can we leave the validation part to the adaptive card parser? expand -> parse -> render; instead of expand & parse -> render?

**Comment by dclaux** [comment]
@nesalang the validation is always left to the AC parser, since the templating engine is a generic JSON-to-JSON transformation engine. The templating engine doesn't know (and shouldn't know IMO) anything about AC.

**Comment by nesalang** [comment]
@dclaux 
the issue creator said that users can **defer** rendering the expanded json until all template data context is ready. and you said, "expression evaluates to undefined or an empty string, the TextBlock isn't rendered, and that's by design end-to-end". Rendering is not the issue here I think. It is the expand operation dropping the template string  when it can't be bound to data that is the issue. I was merely suggesting that we could leave alone the unbound template string, and leave the validation up to adaptive card parser in a case that users attempt to render the invalid adaptive card json.

**Comment by dclaux** [comment]
@nesalang I don't understand what you're saying. The report says:
> I'm using the JS Template SDK in my app to populate template cards with data before posting them (to Webex Teams in my case). I've noticed that if I attempt to expand a template that does not define all of the "templatized" fields in my design the fields that are not populated are deleted.

There is no reference to deferring as far as I can tell.

The bottom line is that the template engine generates a TextBlock that will not be rendered because its text property is undefined (technically the TextBlock is even invalid since text is supposed to be a required property.) The person reporting the issue doesn't want the TextBlock to be dropped. They are suggesting that when the expression for text evaluates to undefined the text property in the template be left unchanged. That is not our design.

**Comment by nesalang** [comment]
@dclaux 
I'm not trying to agonize you.
The report says:
>If the application performs multi-pass templating (as mine attempted to do), there are **additional opportunities to expand** the template **before the render request**.

The desired behavior is templated json will remain as templated json after expand operation as long as there are unbound "templatized" fields.

**Comment by dclaux** [comment]
No matter how many opportunities, templating always happens before rendering, and the problem is it generates a TextBlock with an unspecified text 😊

**Comment by nesalang** [comment]
@dclaux 
but i think dropping the TextBlock when text is set to invalid one "{hello.world}" is the job of render() function. expand() and render() are separate steps.

**Comment by jpjpjp** [comment]
Hi @dclaux and @matthidinger,  I’m the original requester.   In my use case I’m using the sdk in my application logic to transform the card Json (twice) before sending it to a platform to render. 

Perhaps a way to solve this use case is to simply add an optional parameter to the sdk’s template.expand function, ie:

let leaveUnfilledTemplates = true;
let card = template.expand(context, leaveUnfilledTemplates);

This would keep the current behavior of clients that use this.

**Comment by dclaux** [comment]
@jpjpjp your problem is understood, and indeed it seems to me that the right solution is what you suggest, e.g. introduce an option to keep the original value when the expression evaluates to undefined.

We will discuss.

**Comment by dclaux** [comment]
@nesalang I think we ight be talking past each other. But let me try to be more precise.

What you call an invalid expression (namely `"{hello.world}"`) is not necessarily "invalid."

Take this data object:
```
[
  {
    "firstName": "David",
    "lastName": "Claux",
    "shortBio": "David Claux is a PM at Microsoft"
  },
  {
    "firstName": "Matt",
    "lastName": "Hidinger"
  }
]
```

So essentially an array with two objects; the `"shortBio"` property is not required, and for Matt is not present (and is therefore `undefined`).

Now consider this template:
```
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "{shortBio}"
    }
  ]
}
```

- The expression `"{shortBio}"` **is valid**. Sometimes, `shortBio` will be specified in the data object, sometimes it won't
- Thus it needs to evaluate to _something_
- For Matt, that something is `undefined`
- And because of that, template expansion generates the following card:
```
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "David Claux is a PM at Microsoft"
    },
    {
      "type": "TextBlock"
    }
  ]
}
```
When that card is fed to the renderer, the second TextBlock is dropped because it doesn't have a text property.

@jpjpjp wants the generated card to look like this:
```
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "David Claux is a PM at Microsoft"
    },
    {
      "type": "TextBlock",
      "text": "{shortBio}"
    }
  ]
}
```
So essentially he wants the template engine to have an option to leave the expression string as is in the generated payload in the case it evaluates to `undefined`.

**Comment by jpjpjp** [comment]
HI @dclaux, did this ever make it any further than this conversation?

**Comment by dclaux** [comment]
Hi @jpjpjp, I am sorry this is not going faster. I have implemented part of a solution for this - it's in master and [included in the latest templating package on npm](https://www.npmjs.com/package/adaptivecards-templating/v/0.1.1-alpha.1). But at the moment it only works for strings that containg multiple expression, e.g. "{firstName} {lastName}".

The thing is, we will be dropping our custom expression evaluation logic and instead adopt [Adaptive Expressions](https://www.npmjs.com/package/adaptive-expressions) which is more powerful and supports a plethora of functions. While that new model has plenty of advantages, there are some challenges in terms of supporting features such as the one discussed in this thread. I'm working on it though, and hopefully it will be resolved soon.

**Comment by RebeccaAnne** [comment]
Thank you for this issue and feedback. We are not currently focusing on this area. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
