### ISSUE TITLE
[Javascript][Not able to render a TextBlock with no data & $when condition]

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#3688]
# Platform

* JavaScript

# Author or host

Host Name : Microsoft Search

# Version of SDK

adaptivecards-designer@0.7.1

# Details

Not able to render a TextBlock element if I give a $when condition with no data : 
```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "{title}",
            "$when": "{title != \"\"}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
   "$data": {}
}
```

Getting this error : 
`Template expansion error: Invalid value type: undefined`

Not sure if its related with this bug : 
https://github.com/microsoft/AdaptiveCards/issues/3523

**Comment by shalinijoshi19** [comment]
@dclaux / @matthidinger ideas on this one?

**Comment by dclaux** [comment]
@atishayv please try `"$when": "{title != ''}"`

**Comment by atishayv** [comment]
@dclaux Tried with 
```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "{title}",
            "$when": "{title != ''}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
     "$data": {}
}
```

Still getting the same error

**Comment by dclaux** [comment]
I think we have a limitation there is currently no solution for here. I think `title != ''` evaluates to true because `title` is actually `undefined`, but there is no way currently to check for undefined.

This is not something I'm going to be able to fix quickly unfortunately. @matthidinger this is something we might need to discuss, at least look into whether CEL has a solution for it.
