### ISSUE TITLE
[MSTeams][Input.Time] Input.Time property is allowing user to enter text.

### ISSUE THREAD

**Issue by Chekrii** [microsoft/AdaptiveCards#3717]
# Platform

* .NET 
* Bot Framework V4

# Author or host

* Ms Teams

Hi,

We are using Input.Time property in bot but this property is allowing user to enter text and It is not showing 24 hours time format.

Please help with this.

Thanks

![Alarm](https://user-images.githubusercontent.com/49824279/72146253-1196f800-33c2-11ea-957b-65728583cde4.PNG)

**Comment by shalinijoshi19** [comment]
Thanks for reporting this @Chekrii . @siduppal this appears to be a Teams issue I think? I just doublechecked the (AC designer)[https://adaptivecards.io/designer] as well as the UWP visualizer and we are correctly not allowing the Input.Time field to accept free-form input.

**Comment by Chekrii** [comment]
Hello,
Any update on this.

**Comment by susanshen96** [comment]
Hi @Chekrii - Teams employs a custom renderer for Input.Time, and in order to align with time input fields in other places on Teams - like creating a meeting - we're using text input for the time HTMLElement. We may tweak the logic a little so that the field clears out/reverts to the default time if there's an invalid value in the field, but so far, we don't have plans to disallow users from typing in random text.

**Comment by shalinijoshi19** [comment]
@Chekrii please refer to the response from @susanshen96 from the Teams team. I am closing this out for now. Please feel free to reopen should you have additional follow up's. Thanks!

**Comment by TejaReddy0226** [comment]
We are using Input.Time property in bot and It is not showing 24 hours time format.
