### ISSUE TITLE
[iOS][ColumnSet] [Column in ColumnSet is not honouring spacing argument]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#3789]
# Platform

* iOS

# Author or host

TeamSpace iOS

# Version of SDK

1.2.6

# Details

In ColumnSet the spacing defined inside a column is not being honoured. For example in the attached JSON, the spacing ('small') defined for text "RE: Here's a sample email" is not being followed. If you notice, there is no space between the envelope-image and the text. Even on changing the spacing to 'large' it makes no difference.
PFA the screenshot and the json:

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/8917620/74646392-c7aee800-519f-11ea-8114-3d10746db4c3.png)
[emailCard.txt](https://github.com/microsoft/AdaptiveCards/files/4213259/emailCard.txt)

**Comment by nesalang** [comment]
@shalinijoshi19 for visibility
@adumrewal 
This isn't bug. The mail image width was set to 25px. The column that contains the image's relative width was set to 1. The following column that contains a TextBlock has the relative width of 20.

So the column with the TextBlock will get 500 px since it's 20 times of 25px of the first column.
But the phone's width is less than that, so iOS UIKit had to make hard choice, and drop the spacing.

If you reduce relative width to 10,  you get this image:
![image](https://user-images.githubusercontent.com/4112696/74770749-b4ecef80-5241-11ea-882e-f3a1951b08ed.png)

**Comment by adumrewal** [comment]
@nesalang you can close this issue.
