### ISSUE TITLE
Different font iOS vs Windows

### ISSUE THREAD

**Issue by sowsan** [Microsoft/AdaptiveCards#382]
Testing with running webchat in Saffari vs Windows Edge, the font is totally different in both platform. Anyway we can specify the font for all platform as same for the texts in adaptive card?

Note: Testing the adapative card in webchat (bot)

**Comment by matthidinger** [comment]
@danmarshall is this doable today with webchat config?

**Comment by mdtauk** [comment]
The idea is for whatever app/platform is hosting the Adaptive Card content, controls the rendering/appearance right?  So using the platform's default font makes sense unless you are developing an app to display it, then you can choose your own font

**Comment by sowsan** [comment]
Thanks , yes i.e. Correct, but we are talking about webchat which I thought it will retain the same style across the browsers.

**Comment by danmarshall** [comment]
To use the same font in WebChat, or any website for that matter, you will need to use a Web Font since the font you specify may not be installed on the platform of your visitors browser. This Web Font would deployed by you on your site, it wouldn't be part of the AdaptiveCards library. 

The BotFramework WebChat does not use any WebFonts natively, that would again, be something for you to customize and deploy on your own. I'd be happy to help further with any other questions you may have.

**Comment by sowsan** [comment]
Thank you , I'm testing with a simple Adaptive Card to render it in the WebChat. Thought that it will render the adapative card as same in any browser as its in webchat. Is this something need to be done in the Adapative Card side ?

**Comment by danmarshall** [comment]
These details are driven by CSS. WebChat [sets the font to `Segoe UI, sans-serif`](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/scss/botchat.scss#L18). You may do the same in your own CSS. However, even WebChat will not display the Segoe UI font on a Mac for example. This would default back to sans-serif.

**Comment by matthidinger** [comment]
This seems external and part of WebChat so I'll close unless told otherwise. Please reopen if I got this incorrect
