### ISSUE TITLE
We need a sample HostConfig containing all tweakable options

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3841]
None of the sample hostconfigs we currently have cover every single configurable option. We should probably have a "kitchen sink" hostconfig for demonstration purposes (h/t: @DeeJayTC).

We don't, for example, have a sample hostconfig that includes the "Highlight" color configuration. There are likely other options that aren't represented.

**Comment by RebeccaAnne** [comment]
For what it's worth, the [testVariantHostConfig.json](https://github.com/microsoft/AdaptiveCards/blob/master/samples/HostConfig/testVariantHostConfig.json) was meant to be that for the purposes of testing all the properties in the test app, although it seems it's not up to date with all the latest properties. It's maybe not serving the exact same purpose (i was intentionally trying to set every value to something different from the default for test purposes, rather than trying to have "realistic" sample values), but we should consider combining/reconciling any host config we make for this bug with that one.

**Comment by paulcam206** [comment]
agreed. I'm thinking we should implement a `Serialize` method on `HostConfig`, and then place it under unit test (to make sure we don't introduce new options without updating tests)...

**Comment by shalinijoshi19** [comment]
@paulcam206 assigning to you
