### ISSUE TITLE
[Windows/UWP] WinUI support for Windows

### ISSUE THREAD

**Issue by mdtauk** [microsoft/AdaptiveCards#3917]
**What platform is your feature request related to? (Delete other platforms).**

* UWP
* WinUI Desktop

**Is your feature request related to a problem? Please describe.**
Are there any plans to add/move to support WinUI over WUXC for future versions

**Describe the solution you'd like**
Stop using the soon to be deprecated Windows.UI Xaml, and move to WinUI 2.x and 3.x in the future.

**Additional context**
As the control designs develop, and new controls are added to WinUI - it will lead to an inconsistent design, and having to roll your own versions of new controls from the UI Library

**Comment by shalinijoshi19** [comment]
Hi @mdtauk; Yes infact we've been talking about this internally esp with regards to pulling in some key accessibility fixes we'd need that are in WinUI but not backported i believe into the Windows.UI.Xaml version(https://github.com/microsoft/AdaptiveCards/projects/15#card-32415361). Thanks for filing this though since it just helps push this up in our consideration list. @RebeccaAnne / @paulcam206 / @matthidinger

**Comment by mdtauk** [comment]
> Hi @mdtauk; Yes infact we've been talking about this internally esp with regards to pulling in some key accessibility fixes we'd need that are in WinUI but not backported i believe into the Windows.UI.Xaml version(https://github.com/microsoft/AdaptiveCards/projects/15#card-32415361). Thanks for filing this though since it just helps push this up in our consideration list. @RebeccaAnne / @paulcam206 / @matthidinger

Glad to know it is under consideration.  I am not sure if the Windows 10X shell is using AdaptiveCards like the Windows 10 Timeline feature does, but it would be nice to see it used more in the OS.

**Comment by shalinijoshi19** [comment]
It's being tracked now i[n our product board also](https://adaptivecards.productboard.com/feature-board/450286-ac-feature-organization/features/4468578/portal?utm_medium=social&utm_source=portal_share)
