### ISSUE TITLE
[.NET][Adaptive card not rendering large images]

### ISSUE THREAD

**Issue by susanshen96** [microsoft/AdaptiveCards#3922]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML

# Author or host
* Microsoft Teams

If you're an author, who are you sending cards to?
* Sending cards through Flow to Microsoft Teams 

# Version of SDK
* 1.2.4 

# Details
A card being sent by the Flow bot contains an image that seems to be exceeding the .NET upper bound for image sizes. The previous behavior on Flow was that the flow would fail, but according to the Flow team, the new behavior is that the image is being stripped out - the flow succeeds but the image does not appear. 

I'm unable to attach the JSON for some reason, but I'd be happy to send it once this bug is triaged. Thanks!

**Comment by YannickRe** [comment]
Since @susanshen96 is reporting this since I raised the issue with the Teams Product Group, I took a deep dive into what could be the code issue here 😀.

I'm trying to post an Adaptive Card from Power Automate into Teams, in Power Automate I input JSON. In this JSON I enter my images as datauri and not as links. Sometimes this works and sometimes the image is just stripped out of the card, breaking the rendering.
Please find the JSON at [adaptivecards.txt](https://github.com/microsoft/AdaptiveCards/files/4489759/adaptivecards.txt)

Now, looking at the code, the culprit is this declaration:
https://github.com/microsoft/AdaptiveCards/blob/df2618fd75a06ab342a702842ddb404fdfc6443a/source/dotnet/Library/AdaptiveCards/AdaptiveImage.cs#L69

The JSON gets deserialized into an AdaptiveCards object, which includes an AdaptiveImage object which as a result tries to load the datauri Url property in the the .NET Uri object.
Seems like Uri has a hardcoded length limit on the strings it accepts through the constructor, [being 65519 characters](https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netframework-4.8#System_Uri__ctor_System_String_).

So although my image is only 89kb, the resulting datauri exceeds the length limit. The serialization doesn't throw an error and everything just continues with the Url property dropped/being null.

**Comment by shalinijoshi19** [comment]
Thanks @YannickRe and @susanshen96 for reporting and the drill down. We will follow up. Indeed this looks like something we should explicitly throw/report on via the APIs instead of the current seemingly non-deterministic behavior. @paulcam206 / @matthidinger / @dclaux Cc.

**Comment by noorsyyad** [comment]
i see this same issue in **.net wpf** platform as well, is there a separate issue tracking for that, if yes can somebody redirect me to that.

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.

**Comment by YannickRe** [comment]
@paulcam206 In my opinion, if it's not fixed the issue should not be closed. It's not because you ignore it that the bug/problem isn't there 😀. I can understand it isn't on the roadmap for now, which is unfortunate, but closing the ticket makes it seem like you don't care at all.
