### ISSUE TITLE
[AdaptiveCards] [Does Adaptive Cards Support Glyph]

### ISSUE THREAD

**Issue by prkudika** [microsoft/AdaptiveCards#3943]
I am looking to use a glyph for an icon. But when I look at the schema https://adaptivecards.io/explorer/ I didn't find anything related to Glyphs. 

Just wanted to know if Adaptive Cards Supports Glyph or not. If not, do we have any plan to support in future?

---
Pradeep

**Comment by BalajiR** [comment]
@prkudika ,
Can u please provide more details on this ? Like 
- Platform you are targeting ?
- What would be the format of such icons you will be using in cards ?

**Comment by shalinijoshi19** [comment]
In addition @prkudika please direct questions to our [stackoverflow forum](https://stackoverflow.com/questions/tagged/adaptive-cards).. 
We don't support glyphs yet, but it is part of our proposed 1.3 roadmap so do stay tuned, and vote for it, including how important it is to you [here](https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/c/23-themeable-icons-glyphs?utm_medium=social&utm_source=portal_share). I am going to go ahead and close this issue out and looking forward to re-engaging with you on stackoverflow/productboard or here on github in case you have bugs or would otherwise like to provide feedback.. 
Many thanks
