### ISSUE TITLE
[MsTeams]Input.Number is not allowing more than 10 numbers

### ISSUE THREAD

**Issue by Chekrii** [microsoft/AdaptiveCards#3957]
# Platform

* .NetCore
* BotFramework V4
# Host
*  MS Teams

Hi All,

I am using Input.Number property to collect the phone number from the user. If the user enters the wrong number then I am pre-populating the same Adaptive card filling the number entered by the user.

If the value of number is more than 10 digits, input.number property is not allowing that number.

Please have a look at the Json:-

` {"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"My mobile number"},{"type":"Input.Number","placeholder":"","value":"**962213213213213**","id":"asdas"}],"$schema":"http://adaptivecards.io/schemas/adaptive-card.json"}`

This is the error message from Teams App studio:-
<img width="358" alt="InputNumber" src="https://user-images.githubusercontent.com/49824279/80270486-41021400-86d6-11ea-8d72-299421876a08.PNG">

Please help.

Thanks.

**Comment by shalinijoshi19** [comment]
Thanks for reporting this @Chekrii. So Input.Number is supposed to be a [Number ](https://adaptivecards.io/explorer/Input.Number.html)type- specifically enforced as a double value in most of the renderers, including the .NET one and JS. 
After fixing your card to remove the non-number characters, I was able to see it render successfully on our designer (Adaptivecards.io/designer) as well as a quick app that uses our serialization SDK (.NET SDK v1.2.4) - both parsing values as double types ; 

In addition, I wonder if your problem will go away with the fix for #3829 where our JS renderer will be updated to allow both numbers and strings for backwards compatibility. 

FWIW, I am able to repro the bug in Teams App Studio --> Card Editor for AdaptiveCards so there's definitely more to the integration here that I don't understand.. @siduppal / @dclaux / @matthidinger do you know who owns the code here, what AdaptiveCards renderer package it hooks to,  and where Attachment type is defined (is it one of the built in Framework types?) 

Thanks!

**Comment by Chekrii** [comment]
Hello @shalinijoshi19 , I am not able to render that card in teams using Bot framework.

**Comment by shalinijoshi19** [comment]
Thanks @chekrii; i believe that may be due to #3829. @paulcam206 any updates on that one yet? Thanks

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4773
