### ISSUE TITLE
[Mobile][Image Rendering] [Cards with images don't display images on iOS/Android]

### ISSUE THREAD

**Issue by jpjpjp** [microsoft/AdaptiveCards#4114]
# Platform
* Android
* iOS

# Author or host

Host on Webex Teams

# Version of SDK

We have our own fork of AdaptiveCards@v1.2.6

# Details
When we post cards with images, they are not displayed on mobile devices.

Here is a card displayed on our Mac Client (based on the Javascript Renderer)

![MacCardWithImages](https://user-images.githubusercontent.com/4774656/83784010-53b92280-a65e-11ea-9686-50252fc6394a.png)

Here is the same card displayed on an Android Device:

![AndroidCardWithoutImages](https://user-images.githubusercontent.com/4774656/83784185-616ea800-a65e-11ea-8aac-b47d759b933b.png)

Card used was the Flight Itinerary Example:  https://adaptivecards.io/samples/FlightItinerary.html

Create a free Webex Teams account https://www.webex.com/team-collaboration.html to replicate using the Webex Teams Android or iOS App

**Comment by shalinijoshi19** [comment]
@jpjpjp thanks for reporting this. Do you know if this replicates only in your fork of AC or native renderers that we offer (I believe we can provide access to our visualizer tools/apps to help isolate and identify these issues as well - @jwoo-msft ?)

**Comment by shalinijoshi19** [comment]
@jpjpjp per our conversation over the sync, marking this as external at this point and closing out (since we haven't been able to repro this at our end with stock AC renderers and Visualizer tool app that we use);  Please do reach out and reactivate with additional details  if you do require debugging assistance here or anything we can do to aid in the investigation. Thanks!
