### ISSUE TITLE
[iOS] Ability To Check If Current View's Super Views have a SelectAction

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4168]
**What platform is your feature request related to? (Delete other platforms).**

* iOS

**Is your feature request related to a problem? Please describe.**
I'm creating this issue on behalf of Teams mobile team. Their custom image renderer adds a touch event where users touches on the image, it get triggered. However, this feature is being interfered  with superview's selection action handler if any.

**Describe the solution you'd like**
They want a feature where they can check if a current view's super views have select actions installed.  

**Describe alternatives you've considered**
iOS UIKit's standard prtotocol

**Comment by shalinijoshi19** [comment]
@matthidinger also moved to [productboard](https://adaptivecards.productboard.com/insights/shared-inbox/notes/10011038) in case this needs a broader look.

**Comment by anbah34** [comment]
@jwoo-msft I remember you asking for clarity on this request. The ask here is that when an image is in a column set and also has an action enabled, we would like to have a solution to identify if the parent has a action on it. The reason is Teams today opens the image in full screen when clicked on it. If there is a column action as well then both things happen - Image opens in full screen as well as column action. If there is a way to know that the column set has an action enabled then we would not open the image and give precedence to the action

**Comment by jwoo-msft** [comment]
closed: it's a dupe of #4844
