### ISSUE TITLE
[MsTeams][SignInCard] [Cannot style the title in the SignInCard]

### ISSUE THREAD

**Issue by sanjeev9160** [microsoft/AdaptiveCards#4529]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* MsTeams

# Author or host

Author

If you're an author, who are you sending cards to?
MsTeams

# Version of SDK

NA

# Details

Cannot control the styling in the Sign-In card like the font-size and styling of the title. Not having fine control on the sign-in card gives a very bad experience and very restrictive text to be used in the title. Due to this long titles comes in multiple lines.

**Comment by shalinijoshi19** [comment]
@siduppal is this a feature request on the Teams side?

**Comment by Nikitha-MSFT** [comment]
Signin card does have property title could you please use adaptive card instead of signin card.

Steps to create adaptive card:
**step1**:Here is how you get the Sing In URL. 

> var signInLink = await (turnContext.Adapter as IUserTokenProvider).GetOauthSignInLinkAsync(turnContext, _connectionName, cancellationToken);

**Step2**:Here is how you can create Adaptive card for Sign In action:

> {
>  "type": "AdaptiveCard",
>  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
>  "version": "1.2",
>  "body": [
>  {
>  "type": "TextBlock",
>  "text": "Sign in card",
>  "height": "stretch",
>  "size": "ExtraLarge",
>  "weight": "Bolder",
>  "color": "Dark"
>  }
>  ],
>  "actions": [
>  {
>  "type": "Action.Submit",
>  "title": "Click me for signin",
>  "data": {
>  "msteams": {
>  "type": "signin",
>  "value": "Sing In URL"
>  }
>  }
>  }
>  ]
> }
Could you please check this [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions#adaptive-cards-with-signin-action) for more info?
