### ISSUE TITLE
[Website] Show Card Wizard template is failing with templating enabled

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#4539]
# Platform

* Website: http://adaptivecards-ci.azurewebsites.net/samples/ShowCardWizard.html

Presumably this is because its missing a data payload. Perhaps we can work around it by just providing an empty object `{}`?

![image](https://user-images.githubusercontent.com/1432195/89444547-b5e9de80-d706-11ea-80e3-658d013b9b77.png)

**Comment by paulcam206** [comment]
This didn't repro locally because the local storage bit of the templating checkbox doesn't work locally. I won't try to fix that right now since we're trying to ship. Also, there's unfortunately no smoking gun output about what's wrong here. However, I'm going to *guess* that this is due to `ShowCardWizard.data.json` being a zero-byte file rather than an empty JSON doc `{}`.

**Comment by paulcam206** [comment]
I'll reactivate if my speculative fix doesn't work. :)
