### ISSUE TITLE
Feature Request: Tables

### ISSUE THREAD

**Issue by ongandrew** [microsoft/AdaptiveCards#455]
Currently using AdaptiveCard to information to the user via the Bot Framework. Trying to solve the issue of displaying information that would naturally fit in a tabular format elsewhere, but there is no support for such an element.

Workarounds include:
1) Using ColumnSet define columns and TextBlock elements to simulate rows.
2) Cramming information into the FactSet element.

These are not ideal because:
1) Alignment is not guaranteed. Text truncation could occur unless wrap is set to true, which impacts horizontal alignment. A user selecting text will have a column-first cursor scroll.
2) Limited to a key-value pair structure. No support for more than 2 "columns". Key is bolded and no control over formatting that TextBlock offers.

Some examples of the use cases that we are trying to implement are:
1) User queries an invoice or receipt, the bot returns the line items, which should include elements such as line number, description, quantity, price, value etc.
2) User requests a list of documents relating to a purchase order, the bot returns a list that would contain document ID, document type, date, description etc.

This would be useful for displaying structured data to a user.

**Comment by szul** [comment]
I think all of these can be reasonably accomplished with ColumnSet and the current formatting options with the exception of the text highlighting/selection. As @ongandrew points out, attempting to select a single row will select the entire column(s) to the left up to the row where the selection ends. I don't necessarily like the idea of table structures being explicitly implemented, but in the example of a receipt with multiple columns, I can easily see a usability issue with attempting to select a single line item, but have the cursor selection not give the expected behavior. Thoughts?

An easy example is the [Flight Update](http://adaptivecards.io/samples/#FlightUpdate) sample card. Try selecting just a single passenger row.

**Comment by andrewleader** [comment]
Thanks everyone, we're tracking this table feature here as a potential 1.3 feature: https://portal.productboard.com/adaptivecards/1-adaptive-cards-portal/c/16-simple-table-control-with-a-concept-of-rows-grid
