### ISSUE TITLE
[Templating] Adaptive Cards pre-built functions are not working within $data construct

### ISSUE THREAD

**Issue by sunnymitramsft** [microsoft/AdaptiveCards#4574]
# Platform
* .NET

# Author or host
We are working on Kaizala Low-Code feature in Teams. For chat views in Low-Code apps we use AdaptiveCards.Templating library in .NET

# Version of SDK
AdaptiveCards.Templating NuGet v1.0.1

# Details
None of the pre-built [AdaptiveCards functions](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0) are working within **$data** construct. It's throwing below exception

## Exception:
'${sortBy(createArray(4, 3, 1, 2))}' at line, '1' is malformed for '$data : ' pair

## Sample Card:
```json
{
    "view": {
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [
            {
                "id": "Test",
                "type": "Input.ChoiceSet",
                "style": "expanded",
                "isMultiSelect": true,
                "choices": [
                    {
                        "$data": "${sortBy(createArray(4, 3, 1, 2))}",
                        "title": "Test",
                        "value": "Test"
                    }
                ]
            }
        ]
    }
}
```

**Comment by shalinijoshi19** [comment]
Let me take a first pass and get back on this one while @jwoo-msft is OOF.

**Comment by shalinijoshi19** [comment]
@almedina-ms care to take a look at this today if you get a chance?

**Comment by almedina-ms** [comment]
Adding some information that will help the debugging of this issue

Looks like this line is generating always a string rather than the underlying type needed
```
var (value, error) = new ValueExpression(jpath).TryGetValue(parentDataContext.AELMemory);
```

When this function is called jpath = "${sortBy(createArray(4, 3, 1, 2))}"
And it looks like the underlying implementation is actually parsing the array and generating a list, but the returned value is a string rather than the list as value = "System.Collections.Generic.List`1[System.Object]" and error = null
