### ISSUE TITLE
[JavaScript]Empty text with bold markdown shows a separator

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#4676]
# Platform

* JavaScript

# Author or host

Host Name : Microsoft Search

# Version of SDK

"adaptivecards": "2.0.0-rc.0"

# Details

If a text block is wrapped under bold markdown and has empty text, it shows a separator.

![image](https://user-images.githubusercontent.com/13940020/91399040-e1ba3900-e85a-11ea-9e79-971fcb756603.png)

Here is the adaptive card JSON for it :
```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "TextBlock",
            "text": "__${title}__"
        }
    ],
   "$data": {
       "title" : ""
   }
}
```
Ideally it should show blank text.

**Comment by atishayv** [comment]
CC : @dclaux

**Comment by dclaux** [comment]
@atishayv that's an interesting corner case. Because the title is undefined, the final text is "____" which Markdown processes as a horizontal rule (three or more consecutive _ or * will generate a horizontal rule - https://commonmark.org/help/)

The solution is for you to configure your Markdown processor to not do this. There is nothing that AC can fix here since Markdown processing isn't built into the AC SDK.

**Comment by dclaux** [comment]
There is also a solution based on expressions:
```
"text": "${if(title, '__' + title + '__', ''}"
```
Or something like that. But I don't think it's a practical solution for your use case.

**Comment by atishayv** [comment]
Thanks @dclaux
