### ISSUE TITLE
Pic2card on official website

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#4708]

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/5457426

**Comment by matthidinger** [comment]
@haridas feel free to reference this issue with your PR

**Comment by shalinijoshi19** [comment]
@matthidinger anything else that needs to be done here before we close this out?

**Comment by matthidinger** [comment]
I'll move it to 20.10 and we'll close it when @haridas has things buttoned up

**Comment by haridas** [comment]
@matthidinger  Please review the PR #4893

**Comment by shalinijoshi19** [comment]
@matthidinger this *may* have Accessibility implications - do we know/have we double checked with the SMEs? If not i can spin up a thread real quick..

**Comment by shalinijoshi19** [comment]
@RebeccaAnne FYI around the Accessibility question.

**Comment by shalinijoshi19** [comment]
@matthidinger @haridas since this is pending Accessibility Review slated for this week, I am going to have to move this out to 20.11 :(  -- The good news is that if there are no concerns raised in today's review we can pull this back in and get this checked into main && release/20.10 branches for inclusion in the 20.10 payload; Worst case we bundle this up as part of our 20.11 release next month.

**Comment by shalinijoshi19** [comment]
Moving this out to 21.01 to allow time for accessibility fixes + test passes.

**Comment by haridas** [comment]
The accessibility team has given **test pass** confirmation, we can proceed further on this.

**Comment by RebeccaAnne** [comment]
This has been shipped.
