### ISSUE TITLE
[Android][Input Time] [Input time retrieval format to 24 hour format]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#4892]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Author or host

Microsoft Teams

# Version of SDK

SDK 2.1.0 (ACv1.3)

# Details

The format of the input time retrieved from the rendered card depended on the user's mobile phone time format before this release. eg: If user mobile phone time format is 12 hours, input time retrieved would be in 12 hour format. Similarly for 24 hour format.

In the new SDK, the format of the input time retrieved from rendered card is in 24 hour format irrespective of the user's mobile phone time format. This might lead to regression somewhere.

**Comment by shalinijoshi19** [comment]
@almedina-ms / @golddove FYI; I am approving this for a fix at this point since it seems to be a regression on Android. Can whoever has cycles for this pick it up for fixing? Also note that we should update our public documentation with the decision on how we parse and render dateTime inputs and whether we take the user's datetime settings into account at all. @jwoo-msft FYI.

**Comment by shalinijoshi19** [comment]
@dipja as part of our integration testing can we figure out if this is an upgrade blocker? @sowrabh-msft FYI

**Comment by dipja** [comment]
This actually looks like a fix to bring the same experience across iOS, android and JS. iOS and JS already used to return time inputs in 24 hour format. I believe we can close this one
