### ISSUE TITLE
bot emulator error when i click HttpAction button

### ISSUE THREAD

**Issue by sungnoone** [Microsoft/AdaptiveCards#497]
[16:31:12] [err-client] Uncaught TypeError: Observable_1.Observable.ajax is not a function C:\Users\hl\AppData\Local\botframework\app-3.5.29\resources\app\node_modules\botframework-webchat-speech\built\AdaptiveCardContainer.js 40 33 {}

**Comment by danmarshall** [comment]
Hi @sungnoone Thank you for filing this. Can you provide the JSON of your Adaptive Card?

**Comment by sungnoone** [comment]
https://github.com/Microsoft/BotFramework-WebChat/blob/master/AdaptiveCards.md
Action.Http  Not supported in WebChat? really?

**Comment by danmarshall** [comment]
He @sungnoone - thank you for pointing this out. I will get the Bot Framework documentation to state this more clearly, that `Action.Http` is the only feature not supported by WebChat.

The reason is, that your bot will want to know the status of any http request. If the WebChat were to simply make an Ajax call, then you will need custom JavaScript to handle the http response. And this is precisely the kind of logic that belongs in your bot, so that your bot knows all of the state of the conversation.
