### ISSUE TITLE
[JS] Spurious duplicate Id warning on templated card

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4983]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] JavaScript

# Details

When loading the Show Card Wizard card via the New Card dialog, because all Ids are set to ${Id}, a warning about duplicate ids is shown. This warning doesn't apply as once the data is applied all Ids are unique.

![image](https://user-images.githubusercontent.com/9091833/97499651-77417a00-192b-11eb-80da-c8628f3c5f66.png)

**Comment by shalinijoshi19** [comment]
@dclaux is this something that we can address for 20.11 or should i move this out to 20.12? tx

**Comment by dclaux** [comment]
This is quite complicated to fix because it's related to templating. Besides, it's a widespread issue (you'll also get a warning if you use an expression for the "color" property of a TextBlock for instance) and not limited to Id.

Given the solution will be costly and I think it's very low priority, let's push, and honestly I don't expect to fix it anytime soon for now.

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
