### ISSUE TITLE
[JS][Accessibility] [hyperlinks i.e. ac-anchor does not allow to set aria-label property]

### ISSUE THREAD

**Issue by niravk-microsoft** [microsoft/AdaptiveCards#5074]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] JavaScript

# Author or host

We are using JS Renderer to render adaptive cards and we are also sending adaptive cards json to Outlook. Also plan is to send Adaptive cards to teams as well

If you're an author, who are you sending cards to?

Outlook and future plan is to send to teams

# Version of SDK

Adaptive cards 2.0.5

# Details

Currently we are not able to set aria-label property for hyperlinks through adaptive cards json.

**Comment by dclaux** [comment]
@niravk-microsoft could you elaborate on what exactly you would like to be able to do?

There are only two ways <a> tags are generated by the JS SDK:
- Via Markdown processing, in which case the best that could be done would be to set the aria-label to the same thing as the link's description. That would be useless since the link's description is already what is read by Narrator
- On `TextRun`s that have their `selectAction` property set. In that case, the aria-label is already set to the selectAction's title property.

Or are you asking for a new property that can be explicitly specified in the AC payload to define an "accessible label"?

**Comment by RebeccaAnne** [comment]
@niravk-microsoft Please see @dclaux's comment above and let us know if this is still and issue for you.
