### ISSUE TITLE
[JavaScript][Input.Number] [Type of value has changed with latest update]

### ISSUE THREAD

**Issue by aroraketan** [microsoft/AdaptiveCards#5111]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] JavaScript

# Author or host

Host: Microsoft Teams (multi-window).

# Version of SDK

JS v2.5.0.

# Details

The `value` prop of **Input.Number** has changed from `string` type in v1.2.5 to `number | undefined` type in v2.x.
This can potentially break existing host scenarios.
![image](https://user-images.githubusercontent.com/16015962/100321936-7878cc00-2fe9-11eb-9d7a-3d9d45ac3ae3.png)

**Comment by shalinijoshi19** [comment]
@dclaux isn't this related to the Input.Number string vs int discussions we'd been having as part of #3287 earlier this year.. I know we were going to modify the code to accept both number and string types for backwards compatibility. Is that something that is potentially addressed with #5093 ?

**Comment by dclaux** [comment]
@aroraketan @shalinijoshi19 this is by design. The behavior was changed because the JS SDK's behavior didn't match that of the other SDKs.

**Comment by shalinijoshi19** [comment]
@paulcam206 to pick this up to address the breaking change aspect of the original change for JS.

**Comment by paulcam206** [comment]
also need to update schema and enumerate proximal changes

**Comment by dclaux** [comment]
@shalinijoshi19 what is there to address?

**Comment by shalinijoshi19** [comment]
Referencing #3829 which was the issue filed by the BotFramework team around the same issue. @paulcam206 / @dclaux FYI.

**Comment by shalinijoshi19** [comment]
@paulcam206 any updates on this?

**Comment by shalinijoshi19** [comment]
@aroraketan [Input.Number[(https://adaptivecards.io/explorer/Input.Number.html) is expected to be a number type per our schema.  Infact we had inadvertently broken the 1.x series at some point to switch from accepting Input.Number as number only to string causing a botframework scenario break as reported in #3287 and leading to an inconsistency in the JS renderer; We've since addressed that discrepancy in the JS renderer and the 2.x series now matches our schema and other renderers around Input.Number handling.
@dclaux pls correct me if i am wrong here 
@paulcam206 FYI; Doesnt appear we have anything to do here.

**Comment by shalinijoshi19** [comment]
@sowrabh-msft FYI..

**Comment by shalinijoshi19** [comment]
> @aroraketan [Input.Number](https://adaptivecards.io/explorer/Input.Number.html) is expected to be a number type per our schema.
> 
> * Infact we had inadvertently broken the 1.2.x series at some point to switch from accepting Input.Number as number only in 1.2.0 to string starting likely with 1.2.3, causing a botframework scenario break as reported in #3287 and leading to an inconsistency in the JS renderer;
> * We've since addressed that discrepancy in the JS renderer and the 2.x series now matches our schema and other renderers around Input.Number handling.
> 
> @dclaux pls correct me if i am wrong here
> @paulcam206 FYI; Doesnt appear we have anything to do here.

@aroraketan / @sowrabh-msft updates on this one: 
So per our offline conversation on this one, it turned out not about the actual Input.Number schema but the transformed callback data type that is passed in to the host Submit.Action callbacks in case of Input.Number here and the type of *that* object that was divergent and inconsistent with other platforms on JS. 
This inconsistency has now been reverted and JS back to passing the Input.Number as a string to the Action.Submit callback in the host. 
Meanwhile longer term we realize it's an awkward roundtripping story and we are tracking addressing that experience with #5135 .
