### ISSUE TITLE
[Designer] [adaptivecards.io: Sample Card are not working for outkook client]

### ISSUE THREAD

**Issue by saidevgit** [microsoft/AdaptiveCards#5117]
I have taken a sample card from here

https://adaptivecards.io/samples/ExpenseReport.html

But when I am trying to use for out look client with version 1.0 it gives below error.

[Parse] Property "bleed" is supported in version 1.2, but you are using version 1.0.
[Parse] Property "height" is supported in version 1.1, but you are using version 1.0.
[Parse] Unknown element type "ActionSet". Fallback will be used if present.

![image](https://user-images.githubusercontent.com/25056448/100868550-c302b880-34c1-11eb-8566-551fd9627237.png)

**Comment by shalinijoshi19** [comment]
Hi @saidevgit ; these warnings you are seeing are by design - the sample cards surfaced on our website are those that showcase features corresponding to our latest released schema (vis 1.3) and may not work for all host configurations that are exposed on the designer without the warnings surfacing. And that's the experience that the customer using these new features in their card would see today on these hosts including Outlook. It does render the elements it does understand though so that should still be helpful if all you were looking to see was to try the card out, I hope? 

Btw normally if you were interested in using an older version of the sample that works without warnings on the designer one option would be to grab it from the [v1.0 folder](https://github.com/microsoft/AdaptiveCards/tree/main/samples/v1.0/Scenarios) (the version of the schema that outlook currently supports) - 
Hey @matthidinger / @dclaux  do we know if there is/was a v1.0 version of the Expense Report sample handy for @saidevgit to use at all?

**Comment by dclaux** [comment]
@saidevgit as @shalinijoshi19 wrote those warnings are by design.

Outlook's support for Adaptive Card is currently limited to version 1.0 plus some Outlook-specific features that the designer doesn't support. Unfortunately that is a bit problematic with ActionSet because Outlook does support it but technically it wasd only introduced in AC v1.1 - that is somewhat of a bug that should probably be fixed.

If you are designing cards specifically for Actionable Messages, there is a dedicated tool for that purpose here: https://amdesigner.azurewebsites.net/

**Comment by saidevgit** [comment]
Thanks for your response. I have designed the card using https://amdesigner.azurewebsites.net/ and when am trying to use in https://adaptivecards.io/ "to create  json data to bind" it gives errors and look at feel of the card also get broken in the designer. But if I send the card as email to outlook from the amddesigner it shows correct.

1. We are designing card (2-3 pages of data in he email with expand collapse, table, different actions et.c) with  for our enterprise customers (5000+) targeted to Outlook client. Which tool amdesigner or adaptivecards.io should be used to design in this scenario?
2 How do I ensure all cards developed in https://amdesigner.azurewebsites.net/ will support outlook client?
3. How do I test json data bind in amddesigner similar to adaptivecards.io or do you have any other tool to help me with that. Else we have to spend lot of time to manually bind test which will take lot of time.

**Comment by mohitc16** [comment]
@saidevgit, Thanks for your queries.
 
1.	For all actionable emails that will be sent to Outlook, we recommend using our AM Designer portal. You can preview the look and feel of your cards on both desktop and mobile screens via AM Designer, and the emails rendered on Outlook would exactly be the same.
2.	Outlook currently supports only Adaptive Cards 1.0. We currently don’t support data binding on Outlook for Actionable Messages.
 
However, do reach out to us onboardoam@microsoft.com with your scenario details and requirements, and our team will be glad to assist you.
