### ISSUE TITLE
[iOS][isVisible:false rendering issue] [Rendering of hidden components conflicts with animations]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#5123]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Author or host

Host - Teams iOS client

# Version of SDK

latest main

# Details

Suppose you have a hidden element in the card (set using isVisible:false tag). If the render function is called using an animation, it results in the hidden components being visible on the device/simulator. (This could be a potential Apple issue as well).

**Repro steps:**
In ViewController wrap the code for adaptive card rendering with this animation block:

```
[UIView animateWithDuration:0 animations:^{​​
        renderResult = [ACRRenderer render:cardParseResult.card
                                    config:hostconfigParseResult.config
                           widthConstraint:kAdaptiveCardsWidth
                                  delegate:self];
    }​​];
```

CardJson:
```
{
  "body": [
    {
      "separator": true,
      "text": "Please select an item from the list.",
      "weight": "bolder",
      "type": "TextBlock",
      "spacing": "none"
    },
    {
      "items": [
        {
          "separator": true,
          "text": "PAGE 1 of 3. Showing results 1-4 of 11 ",
          "weight": "bolder",
          "type": "TextBlock",
          "spacing": "none"
        }
      ],
      "id": "page1",
      "type": "Container"
    },
    {
      "id": "page2",
      "isVisible": false,
      "items":[
        {
          "separator": true,
          "text": "PAGE 2 of 3. Showing results 5-8 of 11 ",
          "weight": "bolder",
          "type": "TextBlock",
          "spacing": "none"
        }
      ],
      "type": "Container"
    }
  ],
  "type": "AdaptiveCard",
  "version": "1.2"
}
```
Screenshot of the issue:
![Screenshot 2020-12-02 at 6 20 05 PM](https://user-images.githubusercontent.com/8917620/100874843-2c3af980-34cb-11eb-8142-79c9f8c4cc71.png)

Correct Behaviour:
![Screenshot 2020-12-02 at 6 21 05 PM](https://user-images.githubusercontent.com/8917620/100874852-2fce8080-34cb-11eb-91d2-8bb81c36b43d.png)

Please let me know if you need more details.

**Comment by shalinijoshi19** [comment]
@jwoo-msft have you run into this before at all? Thoughts?

**Comment by jwoo-msft** [comment]
@shalinijoshi19,

I have discussed this issue with @adumrewal.
It's possible that it's an Apple issue. I'm going to repro the issue, and we have a repro step, I will update the thread once I'm done with accessibility issues.

**Comment by RebeccaAnne** [comment]
Scheduling for 21.02 as this is a P0 Teams ask.

**Comment by jwoo-msft** [comment]
@adumrewal 
I'm not sure the example given above is valid since the animation block doesn't seem to have one of the valid [animatable properties](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/AnimatableProperties/AnimatableProperties.html).

So I updated the sample app to use UITableView and used `reloadRowAtIndexPaths: WithRowAnimation`. While I was testing it, I did notice the behavior. However, in my case, it was due to a sync issue in the sample app. The reloading and rendering calls were out of sync.  After I sorted out the sync issue in the sample app. I didn't observe such issues. Please take a look.https://github.com/microsoft/AdaptiveCards/blob/d57d33686ebbda23b91a6e6164a71d9fa169d08e/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m#L510
Please note that `UITableViewRowAnimationNone` is currently used because the animation is used for the scrolling in the next line.

**Comment by jwoo-msft** [comment]
@adumrewal 
I'm closing this issue as mentioned above & feel free to open it.

**Comment by adumrewal** [comment]
@jwoo-msft what happens if the withRowAnimation is not `None`...like `Automatic` maybe? Does it render correctly after fixing the sync issue?
Also, fyi @VikrantSingh01, this is the hidden element issue. Can you please tag Linda so that she can then investigate it on Teams.

**Comment by jwoo-msft** [comment]
Hi @adumrewal,

I haven't tried all of the enumeration's values but the ones I tried such as UITableViewRowAnimationTop,
    UITableViewRowAnimationBottom and etc,  all worked as expected.
c.c. @lindach167
