### ISSUE TITLE
[Inconsistency] Action.Submit and Input.Number is a bit "strange"

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#5135]
# Platform

Input gathering for Action.Submit is a bit "strange" and we don't properly document the strangeness. We should discuss whether we should change the behavior, and regardless of the outcome we need to document the behavior.

## Discussion

Right now, the type of the `Input.Number` `value` property is different when used to **set the initial value** and **when serializing it during `Action.Submit`**

**Incoming**: value must be a `number`
**Outgoing** Action.Submit: value gets serialized into a string

- [ ] Should incoming `Input.Number` `value` support `number|string` for better round-trip support?
- [ ] Clarify `Input.Number` docs to specify the supported formats for incoming value and outgoing 
- [ ] Update `Action.Submit` docs to clarify the the submit behavior and serialization format for all Inputs

**Comment by jonmill** [comment]
This is bigger than just Input.Number, so we'll fix this as part of a broader convergence effort.

**Comment by MatthiasGwiozda** [comment]
We are using the values of number - fields. This inconsistency is causing often major problems for us. 

When updating adaptive - Cards to a newer version, the types of some fields are changing strangely very often. Sometimes the webchat - frontend doesn't render the values because a number - field gets a string - value (for example "123"). In older versions of adaptive - cards this is completly fine while in newer versions the value is thrown away by the adaptivecard.

It's a great idea to allow string AND number types for number inputs so that we doesn't have worry about changing types of input - fields.
