### ISSUE TITLE
[.NET] Generated .xml files

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#5157]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] .NET 

# Details

When building .NET, the following .xml doc files are generated. These should either be not generated or deleted, added to the repo, or added to .gitignore to avoid noise:

```
        dotnet/Library/AdaptiveCards.Templating/docs/AdaptiveCardsTemplate.xml
        dotnet/Library/AdaptiveCards/docs/AdaptiveCards.xml
```

**Comment by paulcam206** [comment]
for reference, they're *supposed* to get deleted

https://github.com/microsoft/AdaptiveCards/blob/9e898e5eeec12e3be0f2cdfd9d757bc364c1af41/source/dotnet/Library/AdaptiveCards/AdaptiveCards.csproj#L18-L19

not sure why they aren't. ultimately, it's not really important. we can add them to the project or ignore them. it's not really interesting to track changes over time, though, since they're generated files...
