### ISSUE TITLE
[Teams][Accessibility] [Focus should return to adaptive card after closing date picker]

### ISSUE THREAD

**Issue by lindach167** [microsoft/AdaptiveCards#5205]
[focusDatePickerCardJson.txt](https://github.com/microsoft/AdaptiveCards/files/5718331/focusDatePickerCardJson.txt)

https://user-images.githubusercontent.com/29580478/102666487-eb361c80-413b-11eb-95d0-bde1d04e2bf0.MP4

# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Author or host

Host - Teams Mobile

# Version of SDK

1.2

# Details

This is a ship blocking issue for an app that is aiming to release on Teams Platform. Please see attached video and adaptive card JSON. The focus does not return to the adaptive card after choosing a value from the date picker. User cannot continue in their workflow to complete the scenario. Please see attached video and the JSON for the adaptive card.

**Comment by jwoo-msft** [comment]
@lindach167
cc. @RebeccaAnne for visibility
This issue has been fixed in our latest accessibility push. The fix is included in our latest release (renderer version 2.4.6) which is being integrated into Teams.

https://user-images.githubusercontent.com/4112696/104499730-63083300-5592-11eb-9a5b-7bb911abfd6b.mov
