### ISSUE TITLE
Image urls that include spaces are not being rendered in ios/android renderer

### ISSUE THREAD

**Issue by riarenas** [microsoft/AdaptiveCards#521]
investigate url encoding the strings from the shared model as a potential solution.

**Comment by matthidinger** [comment]
@riarenas is this still open?

**Comment by riarenas** [comment]
This was a report I got from Joseph when he was working on the renderer. I'll double check with the visualizers.

**Comment by almedina-ms** [comment]
Tested it on Android and ios and currently only iOS renderer fails to display the image

**Comment by nesalang** [comment]
I had the logic to deal with that, but Ben didn't like the idea of renderer doing such work, so I removed it.

**Comment by nesalang** [comment]
How should we handle if uri is not conforming to [https://www.ietf.org/rfc/rfc2396.txt](RFC 2396)? space is not legal character, and must be percent encoded. does it make sense to add validation at shared code?

**Comment by shalinijoshi19** [comment]
1. Agreed with @nesalang around having validation of these common content issues in a shared common library. @RebeccaAnne / @paulcam206 FYI -- some potential places we could consider abstracting out parsing failures/content formatting issues in the sharedmodel --

2.  I do feel though we need similar checks on the renderer size as well as the serialization library. What is preventing the renderer from misbehaving due to JSON that wasnt formed using our serialization library/object model?  Thoughts ?

**Comment by shalinijoshi19** [comment]
@nesalang is this something that you are looking into already?

**Comment by nesalang** [comment]
@shalinijoshi19, I'm not looking into this issue anymore. This bug was filed internally (by our team) when there were no resource resolvers for images. since we have images resolvers, this is less of issue; the resource resolvers provided by host will make decisions based on their needs.

We can make the default behaviors more robust. one option is strictly enforcing RFC 2396, and dropping the non-compliant images. currently, we replaced the spaces in urls in sample jsons with %20.
