### ISSUE TITLE
[Teams][UX overlap] [AdaptiveCard drop down choices are hidden behind the iOS Keyboard when keyboard is raised]

### ISSUE THREAD

**Issue by lindach167** [microsoft/AdaptiveCards#5276]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

- Host - Teams Mobile

If you're an author, who are you sending cards to?

# Version of SDK

1.2

# Details

The issue is that when using Input.ChoiceSet on iOS, the native picker overlaps the content on the screen, causing the user not to see the original content. I tested the date picker and it seems to correctly push up the content instead of overlapping. Joseph Woo also checked this issue and said it was not something that was fixed in 1.3

See attached card JSON and repro video
[SampleAdapativeCardJSON.txt](https://github.com/microsoft/AdaptiveCards/files/5816253/SampleAdapativeCardJSON.txt)

https://user-images.githubusercontent.com/29580478/104631984-e3419d80-5651-11eb-895b-99802586471f.MP4

**Comment by shalinijoshi19** [comment]
@jwoo-msft another one from Teams iOS. Can you please take a first pass at this? Thanks.

**Comment by shalinijoshi19** [comment]
@lindach167 is there anything needed of us here esp if this is a no repro on 1.3 bits? @jwoo-msft ?

**Comment by linda167** [comment]
@shalinijoshi19 Joseph said this does repro in 1.3 if I'm not mistaken.

**Comment by jwoo-msft** [comment]
@lindach167, I examined this issue, and I found that fixing this issue requires no changes in the SDK. Making changes in the sample app was sufficient. please refer to this [PR](https://github.com/microsoft/AdaptiveCards/pull/5714). The change mentioned fixed all input types that appear from the bottom. Input.ChoiceSet compact style mentioned in this issue does not repro on sample app because the input view appears inline so it doesn't cover the input.
