### ISSUE TITLE
[iOS][Video player] Add more supported video formates.

### ISSUE THREAD

**Issue by Jageen** [microsoft/AdaptiveCards#5388]
## Platform
* iOS

## Background
1. AdaptiveCard is using native video player to play video file.
<img width="552" alt="avplayer" src="https://user-images.githubusercontent.com/5546841/107729650-d25d7800-6d34-11eb-8606-7ce55d03aff8.png">

2. AdaptiveCard only support mp4 as valid video format.
https://github.com/microsoft/AdaptiveCards/blob/248ce558523efc8a79b6bfd44b5be312cd43c347/source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOMediaEvent.mm#L15

3. We can check by AVURLAsset.audiovisualMIMETypes() that it can support following video mimeTypes.

> video/quicktime, video/mp4, video/avi, video/x-m4v

## Request
Can we unleashed Video player by allowing it to play other remaining supported mimetypes ?

**Comment by jwoo-msft** [comment]
@jwoo-msft

**Comment by paulcam206** [comment]
@matthidinger might want to comment further here, but this is intentional behavior.

The rationale is that we can't guarantee that other video formats will work on all of the platforms that Adaptive Cards supports. The risk would be that someone authors and tests a card on, say, an Apple device, then sends that card out only to find that Windows platforms don't support quicktime.

**Comment by Jageen** [comment]
understood!, and appreciated your detailed explanation.
