### ISSUE TITLE
[Designer] Color definitions limitations and suggestion

### ISSUE THREAD

**Issue by kahopkin** [microsoft/AdaptiveCards#5411]
I think the text color definitions are not very meaningful, and also I think we should be able to use HEX color codes for the color selections and not be boxed into just a handful of colors that might not work for us.

**Comment by paulcam206** [comment]
Hello @kahopkin - appreciate this feedback.

Part of the rationale behind having semantic color names rather than allowing for free form RGB color definitions is that it allows a card to be displayed with colors that adapt to the apps hosting them. Consider if instead of the `good` color definition a card author specified a nice dark green text color. The card might look good in their situation, but what happens when that same card is hosted in an app using a dark theme? The card could end up being rendered in such a way that the text would be difficult to read. By using semantic colors, `good` can be a nice dark green in light-colored hosts and perhaps a nice light green in dark-colored hosts.

Additionally, this allows hosts to have various card colors match the theme of the surrounding app, which wouldn't be possible if card authors specified arbitrary RGB colors.

@matthidinger - care to add anything here?
