### ISSUE TITLE
[Adaptive Card] [Plans for dialog or pop-up]

### ISSUE THREAD

**Issue by jychaaacha** [microsoft/AdaptiveCards#5543]
[Your detailed feedback here]

I'm using adaptive card well.
Do you have any plans to provide pop-up(dialog)? 
What time is it scheduled to be provided?

---
* URL: https://adaptivecards.io/explorer/

**Comment by paulcam206** [comment]
Hello @jychaaacha - there are a couple of options here depending on whether you're a card author or a card host. Card authors don't really have a way to specify a popup dialog, and as far as I know, there aren't any current plans to expose that functionality as an explicit element (@matthidinger can confirm). 

If you're a card host, though, there are a couple of options -- first, you can use the hostconfig option `[actionMode](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config#showcardconfig)` set to `popup`, which causes `Action.ShowCard` actions to be presented as a popup dialog rather than an inline card. The second option as a host would be to author your own dialog that hosts cards.

**Comment by jychaaacha** [comment]
If I use the first option, is it right that all Action.ShowCard actions change from inline to popup? I want to use both options. Is there any way to branch the option?

**Comment by paulcam206** [comment]
Unfortunately, there's no way to do that currently. @matthidinger - are we tracking any requests for this functionality? I couldn't find anything on ProductBoard...

**Comment by LOKESHGORLE** [comment]
Hi @paulcam206 , I tried the approach of setting the actionmode as "popup" in web chat bot. I have taken the reference from other [issue](https://github.com/microsoft/BotFramework-WebChat/issues/2034). I tried to change the action mode in the webchat configs for adaptive cards but it didn't work. Did i miss anything or is there any other way to do it in web chat.

**Comment by jonmill** [comment]
This feature is deprecated and is dependent on host support for ShowCard. We are not planning on adding dialog-like elements as of this moment.
