### ISSUE TITLE
In the outlook mobile app on iOS device, adaptive card are not displaying the validations messages that are sent by our api

### ISSUE THREAD

**Issue by premchandpl76** [microsoft/AdaptiveCards#5556]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS

In the outlook mobile app on iOS device, we have an adaptive card and where we are sending messages to the adaptive card for any validation issues by our api. The outlook app on the desktop version displays validations correctly. But the adaptive card on the iOS device is not showing the validation messages.

Even though I selected the value in Input.ChoiceSet, the outlook mobile app in iOS device, is showing the message "All choices in an Input.ChoiceSet must have their title and value properties set.". In the desktop, I am not able to see that message in desktop outlook and everything works fine

Adaptive Card Version we are using was "1.0"

**Comment by paulcam206** [comment]
@premchandpl76 - can you give us a card sample that demonstrates the problem? @jwoo-msft - anything on your radar for this?

**Comment by jwoo-msft** [comment]
@premchandpl76, 
Can you give us more context on the issue? I'm not quite sure about which validation we are dealing with. I initially thought this issue is about an input validation feature we shipped for schema version 1.3, but in the 2nd half of the description, the validation seems to be more about validating the AdaptiveCards at parsing and rendering. Can you provide more context on the issue? Having a payload, version of iOS SDK (if known), use case and etc would really help.
c.c @paulcam206

**Comment by premchandpl76** [comment]
I am able to resolve the issue. These are the following things I need to do to fix my issue:

1. I need to add "isRequired": true for all the fields which are required. This works fine in outlook app for mobile. For desktop outlook, we have written server side validations
2. For the dropdown (ChoiceSet), I need to set some value to title attribute and after that this issue also got resolved: "All choices in an Input.ChoiceSet must have their title and value properties set"
So closing this issue now
