### ISSUE TITLE
[.NET HTML][Actions] Actions appears to be limited to 5 when converting to HTML

### ISSUE THREAD

**Issue by jbp199** [microsoft/AdaptiveCards#5588]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [x ] .NET HTML
- [ ] .NET WPF
- [ ] Android
- [ ] iOS
- [ ] JavaScript
- [ ] UWP

# Author or host

host - the HUB

If you're an author, who are you sending cards to?

# Version of SDK

2.6

# Details

When rendering multiple action buttons, it appears that html is limited to 5:

{
    "type": "AdaptiveCard",
    "actions": [
        {
            "type": "Action.Submit",
            "$data": "${range(0,20)}",
            "title": "${string(add($data, 1))}",
            "id": "pageSelect_${string(add($data, 1))}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}

Try rendering this and you'll get 5 buttons.  Should get 20.

**Comment by paulcam206** [comment]
This is due to the host config defaults for `MaxActions` (docs [here](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config#schema-actionsconfig)):

https://github.com/microsoft/AdaptiveCards/blob/2257e48ae9a795ea33760d442f0a6b1523c6c682/source/dotnet/Library/AdaptiveCards/Rendering/ActionsConfig.cs#L33-L37

You can change the default limit of `5` by supplying an `AdaptiveHostConfig` object to the `AdaptiveCardRenderer` object during construction (or by modifying the value you care about after construction).

Please let us know if you encounter any problems!

**Comment by jbp199** [comment]
Brilliant, thanks Paul!
