### ISSUE TITLE
data binding for numbers broken ?

### ISSUE THREAD

**Issue by IntranetFactory** [microsoft/AdaptiveCards#5645]
When I bind a numeric value to a number the result is empty:    e.g. ` "value": "${quantity}"`

but if there are any additional character besides the bound number value shows e.g. ` "value": "€${amount}"`

![image](https://user-images.githubusercontent.com/7462342/114087521-45f2b000-98b4-11eb-8854-a2e4fc5d1ab5.png)

**Comment by jonmill** [comment]
Thanks for bringing this to our attention. We'll look into this...in the meantime, you should be able to enclose the data in quotes as a workaround.

**Comment by jwoo-msft** [comment]
@IntranetFactory, it's not broken. the type of data was an integer, and the Facts' Value requires a type string. the template expanded to "Value" : 2. then the renderer probably dropped the value field since it doesn't have the required string property.
you can do 
1. change the data to string type as @jonmill  mentioned.
2. use AEL function to convert int to string, [string](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#conversion-functions)  "Value": "${string(quantity)}"
