### ISSUE TITLE
[JS] The `adaptivecards-designer` and `adaptivecards-templating` packages are not configured properly

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#5992]
# Target Platform

- NodeJS

# Problem Description

The `adaptivecards-templating` and `adaptivecards-designer` packages are not configured properly:
- `adaptivecards-designer` includes a useless `peerDependencies` clause and lacks proper `dependencies` to `adaptivecards`, `adative-expressions`, `adaptivecards-templating` and `monaco-editor`
- `adaptivecards-templating` includes a useless `peerDependency` clause

**Comment by anna-dingler** [comment]
Closing issue since peerDependencies are needed per this update from @dclaux -  

"The goal should be that:

- `adaptivecards-designer` has a strong `dependency` on `adaptivecards`, `adaptivecards-templating` and `adaptive-expressions` without embedding a copy of those libraries in its package. It should be the responsibility of the consuming application to load the dependencies

- Same thing for `adaptivecards-templating`, which should have a strong `dependency` on `adaptive-expressions` without embedding a copy of it in its package."
