### ISSUE TITLE
Card versioning and fallback

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#6]
# Problem

If a bot developer absolutely requires a v2 renderer, and fallback would not be appropriate, they can add this attribute and the renderer would output something like “Unfortunately this content couldn’t be displayed”

# Schema 

1. `version` is a required property on all payloads.
1. `minVersion` is an optional property that allows a developer to declare that their card must only be renderered on a supported version.

## Example

```json
{
    "$schema": "../../schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "99.0",
    "minVersion": "99.0",
    "fallbackText": "This card requires Adaptive Cards version 99.0, which probably doesn't exist",
    "body": [
        {
            "type": "TextBlock",
            "text": "THIS SHOULD NOT APPEAR! It should show the fallback text"
        }        
    ]
}
```

## Renderer spec
1. A renderer **MUST** implement a particular version of the schema. 
1. If a renderer encounters a `minRequiredVersion` property in the `AdaptiveCard` that is higher than the supported version, it **MUST** return the `fallbackText` instead.

**Comment by dclaux** [comment]
What is the design for this?

**Comment by Assaya** [comment]
http://adaptivecards.io/

x

**Comment by matthidinger** [comment]
Updated with the spec

**Comment by dclaux** [comment]
@matthidinger I am a bit confused by the spec:
* What is the use of the "version" property?
* Is the other one "minVersion" or "minRequiredVersion"?

My take is:
* A renderer is associated with the version of the schema it implements. That is an internal renderer property, not something that is passed in a payload
* A payload can include a "minVersion" property. In that sitation, the renderer compares it to its internal version. If minVersion is greater than internal version, the renderer only renders fallbackText.

**Comment by matthidinger** [comment]
This is deprecated based on the decision from #965

**Comment by Assaya** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/dc3b2b1d7c",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Angela is tired of keeping Fiverr a secret.
    

    
        Discover the easiest way to hire online freelancers and get 20% off your first order. From marketing to tech, complete all your projects on Fiverr. On budget. On time.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2019, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    
If you would like to unsubscribe and stop receiving these emails click here.

**Comment by Assaya** [comment]
𝒜𝓃𝑔𝑒𝓁𝒶

Forwarded Conversation
Subject: [No-Reply] Test message from G Suite Technical Support
------------------------

From: G Suite Technical Support Test Sender <
noreply-smtptester@googleapps.com>
Date: Sun, 5 May 2019 at 00:38
To: <angela@globalcherry.group>


Dear G Suite customer,

This is a test message sent to you from the G Suite technical support team
to test successful email delivery to your domain’s users.
Typically, this message is received when one of the G Suite domain
administrators on the domain are working with our technical support team
to
set up and/or test successful email delivery to your G Suite users.

No action is required from your side.

If you have any questions or concerns, please follow up with your
organization’s G Suite domain administrators and review relevant open G
Suite email delivery support cases.

Best Regards,
Your G Suite technical support team


----------
From: Angela Westell <angela@globalcherry.group>
Date: Sun, 5 May 2019 at 00:46
To: G Suite Technical Support Test Sender <noreply-smtptester@googleapps.com
>


Coming through
𝒜𝓃𝑔𝑒𝓁𝒶



----------
From: Mail Delivery Subsystem <mailer-daemon@googlemail.com>
Date: Sun, 5 May 2019 at 00:46
To: <angela@globalcherry.group>


[image: Error Icon]
Address not found
Your message wasn't delivered to *noreply-smtptester@googleapps.com*
because the address couldn't be found or is unable to receive email.
LEARN MORE <https://support.google.com/mail/?p=NoSuchUser>
The response was:

The email account that you tried to reach does not exist. Please try
double-checking the recipient's email address for typos or unnecessary
spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser
69sor15063069jaa.7 - gsmtp
