### ISSUE TITLE
[Authoring] Can't parse a type extended from Column

### ISSUE THREAD

**Issue by JonathanWacks** [microsoft/AdaptiveCards#6075]
# Target Application

HTML (Node.js)

# Problem Description

I have created an extension for a Column so that I can dynamically style a particular column.  However, the Column extension is being completely ignored.  It is registered against the Global Registry.

# Expected Outcome

The extended Column to be parsed and rendered as part of the overall ColumnSet

# Actual Outcome

The extended Column is ignored by the parser (and obviously not rendered)

# Repro Steps

Create a type such as follows:
```
class TestColumn extends AdaptiveCards.Column {
	getJsonTypeName(): string {
		return "TestColumn";
	}

	protected internalRender() : HTMLElement | undefined {
		const column = super.internalRender();

		if (column) {
			column.style.backgroundColor = "red";
		}

		return column;
	}
}
```
Attach the type to the global registry:
`AdaptiveCards.GlobalRegistry.elements.register("TestColumn", TestColumn);
`
Add the extended column to the adaptive card:
```
"type": "ColumnSet",
            "columns": [
                {
                    "type": "TestColumn",
                    "items":[
                        {
                            "type": "TextBlock",
                            "text": "Does this work?"
                        }
                    ]                    
                }
            ]
```

# Schema Version

v1.3

**Comment by paulcam206** [comment]
Since `Column`s aren't valid outside of a `ColumnSet`, as currently implemented, `ColumnSet` directly renders its children:

instantiation of `Column` children:

https://github.com/microsoft/AdaptiveCards/blob/a5d337d166d88d1bacad514f7dd01eb849a96abb/source/nodejs/adaptivecards/src/card-elements.ts#L6236-L6251

rendering children:

https://github.com/microsoft/AdaptiveCards/blob/a5d337d166d88d1bacad514f7dd01eb849a96abb/source/nodejs/adaptivecards/src/card-elements.ts#L6289-L6310

Since it can only have `Column` children, it doesn't indirect through the global registry. I would certainly consider taking a PR to update this behavior, but fixing this isn't on our roadmap right now.
