### ISSUE TITLE
[Accessibility][iOS] - Voice over read minutes in TextBlock as "meters"

### ISSUE THREAD

**Issue by rahulpinjani1** [microsoft/AdaptiveCards#6848]
**# Platform**
* iOS

**Target Application**
Please provide the name of the application that is rendering the card (ex: Outlook, Teams, etc)
Teams

**# Version of SDK**
SDK 2.8.0-beata1

**# Issue**
Text showing time in minutes on the card is being read by voiceover as "meters" instead of minutes. Note: If the text shows time in x hours and xx minutes voice over read it correctly as x hours xx minutes

For example
 "39m" is read as "39 meters"
 "1 h 39 m" is read as "1 hour 39 minutes"
 

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by jonmill** [comment]
@rahulpinjani1 - thanks for the bug report! Unfortunately, this is by-design at the moment. Since card authors control the text being displayed, they are responsible for making sure the text is accurate. The narrator and voice-over will be a best-effort solution if the text is unclear, but the solution at this point is to not use abbreviations like "m" that could be ambiguous to the narrator
