### ISSUE TITLE
[Feature Request] Json to HTML should produce consistent div ids

### ISSUE THREAD

**Issue by doug-madden** [microsoft/AdaptiveCards#7207]
### Problem Statement

Every time we convert card data from json to html, the output is different. This makes it very difficult to de-duplicate content captured from Microsoft Teams.

![image](https://user-images.githubusercontent.com/84027155/162749962-e50b922b-eb3b-4223-8400-2407c62a99d8.png)

When we capture data from Teams for eDiscovery purposes, the content is packaged into a file meant for review platforms (usually eml). In order for the card content to be visible in a meaningful way in this file, we have to convert it to html. This conversion to html introduces inconsistent values which makes it very difficult to dedupe the output of 2 different collections for the same date period.

### Proposed solution

Provide a mode that will use an incrementing id for all divs rather than what is seemingly a random assignment of ids.

**Comment by doug-madden** [comment]
Can someone comment if this is within the scope of this project? Or should I be going down a different path to deal with this issue?

**Comment by paulcam206** [comment]
Hmm... I suspect that this is _specific_ generated-id output is from Teams itself (the column separators we create have no `id` and use `class="ac-vertical-separator"`)...

However, we _do_ have some randomly-generated ids. They're of the form `__ac-[uuid]`, and are typically used when generating labels and inputs. In our case, we have to use random ids because we can't make assumptions about the lifetime of our rendering objects or their operating environment.

It's not unusual for a consumer of the JS renderer to render multiple cards and add them to their DOM, so we still need to guarantee uniqueness across multiple renders. It's also not unusual for a consumer to construct one-off instances of the renderer on-demand to perform rendering, so we can't guarantee that our previous internal state will be around. In the case of incrementing ids, we could end up with multiple elements having `id="__ac-0"`, which is bad.

Do you have any facility for post-processing these cards? If you know that they're going to be displayed as just static content in isolation, you could replace these `id`s in order of appearance.

**Comment by doug-madden** [comment]
The teams card content json is the same every time. The original json does not contain those keys or values highlighted in the image. The inconsistencies are only present _after_ converting to html. I wouldn't expect this to be a default functionality. More of a static generator for one-off rendering to archive the content.

I've been considering doing that, the problem is I don't have a general way of knowing which attributes will need to be overridden and which ones won't. Is it safe to say any id attribute (or attribute that ends in id) in an html tag can be replaced?

**Comment by licanhua** [comment]
Possible you can add md5sum(your data) to the data field for ac-vertical-separator or something, then use that field to de-dup.
From AC card itself, we can't guarantee the same id for the same data.

**Comment by paulcam206** [comment]
> I've been considering doing that, the problem is I don't have a general way of knowing which attributes will need to be overridden and which ones won't. Is it safe to say any id attribute (or attribute that ends in id) in an html tag can be replaced?

If the intent is to be able to _display_ a card, it should be safe to replace the `id`s -- as long as you don't need the card to be interactive.
