### ISSUE TITLE
[Feature Request] Custom colors in Adaptive Cards

### ISSUE THREAD

**Issue by nblankenship** [microsoft/AdaptiveCards#7771]
# Platform

Webchat/Teams

# Author or host

Author rendering Adaptive Cards in Webchat (v1.3) and Teams for practitioners

# Issue

**There is currently no way to use custom colors in Adaptive Cards**. This is a huge limitation for authors wanting to uphold **continuous branding** throughout solutions. I found someone else asking for custom colors and Matt Hidinger responded with this link however this product board doesn't seem to work at all for me anymore: https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/c/29-custom-colors-for-text

I also checked the roadmap here on Github but no results showed up regarding custom colors. 

If there is already a feature under consideration for this can a current link be provided? If not, can this be considered?

Thank you!

**Comment by paulcam206** [comment]
Hello @nblankenship -- This request has come up from time to time, and historically we've pushed back against it. I understand the desire for branding consistency, but the "Adaptive" part of "Adaptive Cards" refers to the intent that a card can be authored once and shown in many places in a way that feels native to the card's host. 

Consider what happens when a card author specifies a dark gray custom font color -- what if the card is rendered on someone's device running in dark mode? With semantic colors (e.g. `"warning"`), the rendering host can react to theme changes and high contrast mode to provide a cohesive experience, but with custom colors that becomes much more difficult.

I don't believe this is currently on our roadmap to address, so I'm going to close this issue. However, please feel free to continue the conversation in this issue.

Thanks!
