### ISSUE TITLE
Issue: Adaptive card input element height mismatch while rendering in webchat [Bot framework]

### ISSUE THREAD

**Issue by Lancelot301** [microsoft/AdaptiveCards#7924]
### Target Platforms

Other

### SDK Version

1.3

### Application Name

Webchat

### Problem Description

Hi , I am Trying to create an Adaptive card with two input fields one is a date and another one is choiceSet, It is working fine in designer
like this:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/114400426/192279959-2afee83b-4c23-417a-b661-864974b4f49b.png">

but in webchat there is a mismatch in height of both the element. Can we explicitly set the height of input element? If yes then how?

Any suggestions or reference would be very helpful

Thanks in Advance!

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Sample form"
        },
        {
            "type": "Input.Date"
        },
        {
            "type": "Input.ChoiceSet",
            "choices": [
                {
                    "title": "Choice 1",
                    "value": "Choice 1"
                },
                {
                    "title": "Choice 2",
                    "value": "Choice 2"
                }
            ],
            "placeholder": "Placeholder text"
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "Submit",
            "url": "${viewUrl}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3"
}
```

### Sample Code Language

C#

**Comment by paulcam206** [comment]
> Can we explicitly set the height of input element?

There _is_ a [`height` property for `Input` elements](https://adaptivecards.io/explorer/Input.Text.html), but the valid values are `auto` (the default)  or `stretch` (expands the control to fill available space). However, even with `stretch`, the input fields themselves aren't going to expand in height.

That said, rendering differences between Webchat and the Designer usually need to be fixed by folks working on Webchat.
Please [open a new issue](https://github.com/microsoft/BotFramework-WebChat/issues/new/choose) in their [GitHub repo](https://github.com/microsoft/BotFramework-WebChat/). Thanks!

**Comment by Lancelot301** [comment]
Thanks @paulcam206 for the suggestion. I have opened another issue which you can find it [here](https://github.com/microsoft/BotFramework-WebChat/issues/4422)
