### ISSUE TITLE
.NET support for AdditionalProperties

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#836]
Regarding #234 

I'm still on the fence on how to design this. Are additional properties only valuable if you're creating a custom renderer? If so, in .NET, this could be achieved by creating a subclass with the additional properties you want deserialized, and then override the TypedElementConverter registered parsers.

@anbare thoughts here?

**Comment by anbare** [comment]
True, although additional properties are also valuable for the card authoring side. For example, toast devs will need a way to provide an additional property.

One option could be the toast library we ship extends the existing type in order to add the additional properties, like...

```csharp
new ToastSubmitAction()
{
    Title = "Save",
    Data = data,
    SubmitOptions = new ToastBackgroundSubmitOptions()
}
```

However if you also need to add a Timeline-specific or Skype-specific additional property in the same payload, that system breaks down, since it can only be a `ToastSubmitAction` or `SkypeSubmitAction` and not both.
