### ISSUE TITLE
VS Code : Previewer steals focus all the time from code window

### ISSUE THREAD

**Issue by paulaRichardson** [microsoft/AdaptiveCards#902]
Not sure if this is expected behavior or not, when running the previewer side by side with adaptive card json showing, the previewer always takes focus so you can't actually 'live' type json and see the changes.  So blocks the useful scenario of typing and seeing changes getting updated.

- VS Code (version 1.17.2)
- Adaptive Card Viewer (Version 1.0.7)
- Windows 10
- Using "adaptivecardsviewer.enableautopreview": true,

**Comment by matthidinger** [comment]
Hi @paulaRichardson thanks for letting us know! We will carve off some time for tooling upgrades in the as soon as we can. Definitely accepting PRs for this if folks want to dig in though :)

**Comment by shalinijoshi19** [comment]
@matthidinger do you know where the AC Viewer extension for VS code is maintained at ?

**Comment by matthidinger** [comment]
The source code is in `~/source/vscode` and it's pretty outdated. Two things that would be ideal would be 

1. Update the package dependency to adaptivecards instead of microsoft-adaptivecards
2. Update publisher from tomlm to adaptivecards, but I think we would need a registration in the VS code extension store somehow?

**Comment by jonmill** [comment]
As this is currently owned by Tom and not the AC team, closing
