### ISSUE TITLE
Suggestion: `isMarkdown` field

### ISSUE THREAD

**Issue by synk** [microsoft/AdaptiveCards#983]
## background
In current TextBlock spec, `text` is always handled as markdown.
On the other hand we cannot assume that developers always own their data as markdown format. Especially when integrating existing enterprise database (e.g. product name, product code, descriptions, etc).
It is difficult to force them to escape markdown notations.

### Option A
add `isMarkdown` field to `TextBlock` (default:`true` for compatibillity)
* easy to keep compatibility but not extensible for other formats

### Option B
separate `TextBlock` and `MarkdownBlock`.
* extensible but it will be breaking change

### Option C
add `contentType` field which accept `text/plain` or `text/markdown`
* extensible but it is very noisey to add content type to every `TextBlock`s

**Comment by nesalang** [comment]
I think this is good idea, and like option A.

**Comment by anbare** [comment]
I like Option A under the assumption that we have no plans to support other formats.

However, I believe default should be `false`, since I'd believe it's much more likely that apps will be populating text blocks with dynamic user-provided info and not realize markdown is accidently being processed. Essentially, markdown should be an **opt-in** experience.

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
